<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cohesive\Cohesive.csproj" />
    <ProjectReference Include="..\Cohesive.Transitions\Cohesive.Transitions.csproj" />
    <ProjectReference Include="..\Cohesive.Relations\Cohesive.Relations.csproj" />
    <ProjectReference Include="..\Cohesive.Processes\Cohesive.Processes.csproj" />
    <ProjectReference Include="..\Cohesive.Host\Cohesive.Host.csproj" />
    <ProjectReference Include="..\Cohesive.Storage\Cohesive.Storage.csproj" />
    <ProjectReference Include="..\adapters\Cohesive.Adapters.Cosmos\Cohesive.Adapters.Cosmos.csproj" />
    <ProjectReference Include="..\adapters\Cohesive.Adapters.DurableTask\Cohesive.Adapters.DurableTask.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
