using System.Collections.Immutable;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Options for TypeScript emission.
/// </summary>
public sealed record TypeScriptEmitterOptions
{
    /// <summary>
    /// Output file name.
    /// </summary>
    public string FileName { get; init; } = "cohesive.generated.ts";

    /// <summary>
    /// Line terminator used by the writer.
    /// </summary>
    public string NewLine { get; init; } = "\n";

    /// <summary>
    /// Spaces per indent level.
    /// </summary>
    public int IndentSize { get; init; } = 2;

    /// <summary>
    /// Emits the standard auto-generated banner.
    /// </summary>
    public bool EmitAutoGeneratedHeader { get; init; } = true;

    /// <summary>
    /// External TypeScript modules that own generated declarations for matching shape graph types.
    /// </summary>
    public ImmutableArray<TypeScriptExternalTypeModule> ExternalTypeModules { get; init; } = [];
}
