using System.Text.Json;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Options for TypeScript API client emission.
/// </summary>
public sealed record TypeScriptApiClientEmitterOptions
{
    /// <summary>Optional public JSON contract used for request member names. Null preserves CLR projection.</summary>
    public JsonSerializerOptions? JsonSerializerOptions { get; init; }
    /// <summary>
    /// Output file name.
    /// </summary>
    public string FileName { get; init; } = "api.generated.ts";

    /// <summary>
    /// Relative import path for generated shape types.
    /// </summary>
    public string ShapesImportPath { get; init; } = "./contracts.shapes.generated";

    /// <summary>
    /// Shared HTTP client type alias name.
    /// </summary>
    public string HttpClientTypeName { get; init; } = "ApiHttpClient";

    /// <summary>
    /// Optional module name used to prefix generated metadata exports.
    /// </summary>
    public string? ModuleName { get; init; }

    /// <summary>
    /// Emitted newline sequence.
    /// </summary>
    public string NewLine { get; init; } = "\n";

    /// <summary>
    /// Indentation size in spaces.
    /// </summary>
    public int IndentSize { get; init; } = 2;

    /// <summary>
    /// Emits an auto-generated header when true.
    /// </summary>
    public bool EmitAutoGeneratedHeader { get; init; } = true;
}
