using System.Collections.Immutable;
using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using Cohesive.Api;
using Cohesive.Api.CodeGen;
using Cohesive.CodeGen;
using Cohesive.Model;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Emits a typed Playwright route mock host from a Cohesive API definition.
/// </summary>
public sealed class TypeScriptPlaywrightApiMockEmitter : IApiCodeEmitter
{
    readonly TypeScriptPlaywrightApiMockEmitterOptions options;

    /// <summary>
    /// Creates the emitter.
    /// </summary>
    public TypeScriptPlaywrightApiMockEmitter(TypeScriptPlaywrightApiMockEmitterOptions? options = null)
    {
        this.options = options ?? new TypeScriptPlaywrightApiMockEmitterOptions();
    }

    /// <inheritdoc />
    public string Language => "typescript-playwright";

    /// <inheritdoc />
    public CodeEmission Emit(in ApiCodeGenerationRequest request)
    {
        var models = BuildOperationModels(request.Definition);
        var modulePrefix = ToPascalCase(options.ModuleName);
        var writer = new PooledCodeWriter(
            initialCapacity: EstimateInitialCapacity(request.Definition),
            indentSize: options.IndentSize,
            newLine: options.NewLine);

        try
        {
            if (options.EmitAutoGeneratedHeader)
            {
                writer.WriteLine("/* <auto-generated/> */");
                writer.WriteLine();
            }

            WriteImports(ref writer, models);
            WriteEndpointTypes(ref writer, modulePrefix, models);
            WriteMockTypes(ref writer, modulePrefix, models);
            WriteResultBuilders(ref writer, modulePrefix, models);
            WriteInstallFunction(ref writer, modulePrefix);
            WriteRouteHandler(ref writer, modulePrefix);
            WriteMatcher(ref writer, modulePrefix, models);
            WriteDecoders(ref writer, modulePrefix, models);
            WriteRuntimeHelpers(ref writer, modulePrefix, models);

            return new CodeEmission(
                language: Language,
                documents: [new GeneratedCodeDocument(options.FileName, writer.ToString())]);
        }
        finally
        {
            writer.Dispose();
        }
    }

    /// <summary>
    /// Emits a definition directly.
    /// </summary>
    public CodeEmission Emit(ApiDefinition definition) => Emit(new ApiCodeGenerationRequest(definition));

    void WriteImports(ref PooledCodeWriter writer, IReadOnlyList<OperationModel> models)
    {
        writer.WriteLine("import type { Page, Request, Route } from '@playwright/test';");

        var imports = CollectTypeImports(models);
        if (imports.Length > 0)
        {
            writer.Write("import type { ");
            for (var i = 0; i < imports.Length; i++)
            {
                if (i > 0)
                    writer.Write(", ");

                writer.Write(imports[i]);
            }

            writer.Write(" } from ");
            writer.Write(Quote(options.ShapesImportPath));
            writer.WriteLine(";");
        }

        writer.WriteLine();
    }

    static void WriteEndpointTypes(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.Write("export type ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey =");
        writer.PushIndent();
        if (models.Count == 0)
        {
            writer.WriteLine("never;");
        }
        else
        {
            for (var i = 0; i < models.Count; i++)
            {
                writer.Write("| ");
                writer.Write(Quote(models[i].Key));
                writer.WriteLine(i == models.Count - 1 ? ";" : string.Empty);
            }
        }
        writer.PopIndent();
        writer.WriteLine();

        writer.Write("export const ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds = {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write(models[i].Key);
            writer.Write(": ");
            writer.Write(Quote(models[i].Operation.Id.Value));
            writer.WriteLine(",");
        }
        writer.PopIndent();
        writer.Write("} as const satisfies Record<");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey, string>;");
        writer.WriteLine();

        WriteScopeMetadata(ref writer, modulePrefix, models);
        WriteEndpointMapInterface(ref writer, modulePrefix, models, "Route", static model => model.RouteType);
        WriteEndpointMapInterface(ref writer, modulePrefix, models, "Query", static model => model.QueryType);
        WriteEndpointMapInterface(ref writer, modulePrefix, models, "Body", static model => model.BodyType);
        WriteEndpointMapInterface(ref writer, modulePrefix, models, "ResponseBody", static model => model.ResponseBodyType);
        WriteResultMetadata(ref writer, modulePrefix, models);
        WriteResultBuilderInterface(ref writer, modulePrefix, models);
    }

    static void WriteScopeMetadata(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiScopePolicyMetadata {");
        writer.PushIndent();
        writer.WriteLine("readonly kind: string;");
        writer.WriteLine("readonly cardinality: 'single' | 'multiple';");
        writer.WriteLine("readonly binding: 'ambient' | 'header' | 'query' | 'route' | 'body' | 'resource';");
        writer.WriteLine("readonly access: 'requireSelected' | 'filterToAccessible' | 'validateAccessible';");
        writer.WriteLine("readonly singleScopeParameterName?: string;");
        writer.WriteLine("readonly multipleScopesParameterName?: string;");
        writer.WriteLine("readonly scopeModeParameterName?: string;");
        writer.WriteLine("readonly resourceParameterName?: string;");
        writer.WriteLine("readonly resourceDerivation?: { readonly strategy: string; readonly format?: string; readonly scopeField?: string; };");
        writer.WriteLine("readonly allowDefaultScope: boolean;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiScopePolicyByEndpoint {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write("readonly ");
            writer.Write(models[i].Key);
            writer.Write(": readonly ");
            writer.Write(modulePrefix);
            writer.WriteLine("ApiScopePolicyMetadata[];");
        }
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export const ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiScopePolicies = {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            var model = models[i];
            writer.Write(model.Key);
            writer.WriteLine(": [");
            writer.PushIndent();
            for (var policyIndex = 0; policyIndex < model.Operation.ScopePolicies.Count; policyIndex++)
                WriteScopePolicy(ref writer, model.Operation.ScopePolicies[policyIndex]);
            writer.PopIndent();
            writer.WriteLine("],");
        }
        writer.PopIndent();
        writer.Write("} as const satisfies ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiScopePolicyByEndpoint;");
        writer.WriteLine();
    }

    static void WriteScopePolicy(ref PooledCodeWriter writer, ApiScopePolicy policy)
    {
        writer.Write("{ kind: ");
        writer.Write(Quote(policy.ScopeKind));
        writer.Write(", cardinality: ");
        writer.Write(Quote(ToCamelCase(policy.Cardinality.ToString())));
        writer.Write(", binding: ");
        writer.Write(Quote(ToCamelCase(policy.Binding.ToString())));
        writer.Write(", access: ");
        writer.Write(Quote(ToCamelCase(policy.Access.ToString())));
        WriteOptionalScopePolicyProperty(ref writer, "singleScopeParameterName", policy.SingleScopeParameterName);
        WriteOptionalScopePolicyProperty(ref writer, "multipleScopesParameterName", policy.MultipleScopesParameterName);
        WriteOptionalScopePolicyProperty(ref writer, "scopeModeParameterName", policy.ScopeModeParameterName);
        WriteOptionalScopePolicyProperty(ref writer, "resourceParameterName", policy.ResourceParameterName);
        WriteResourceScopeDerivationProperty(ref writer, policy.ResourceDerivation);
        writer.Write(", allowDefaultScope: ");
        writer.Write(policy.AllowDefaultScope ? "true" : "false");
        writer.WriteLine(" },");
    }

    static void WriteResourceScopeDerivationProperty(ref PooledCodeWriter writer, ApiResourceScopeDerivation? derivation)
    {
        if (derivation is null)
            return;

        writer.Write(", resourceDerivation: { strategy: ");
        writer.Write(Quote(derivation.Strategy));
        WriteOptionalObjectProperty(ref writer, "format", derivation.Format);
        WriteOptionalObjectProperty(ref writer, "scopeField", derivation.ScopeField);
        writer.Write(" }");
    }

    static void WriteOptionalObjectProperty(ref PooledCodeWriter writer, string name, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;

        writer.Write(", ");
        writer.Write(name);
        writer.Write(": ");
        writer.Write(Quote(value));
    }

    static void WriteOptionalScopePolicyProperty(ref PooledCodeWriter writer, string name, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;

        writer.Write(", ");
        writer.Write(name);
        writer.Write(": ");
        writer.Write(Quote(value));
    }

    static void WriteEndpointMapInterface(
        ref PooledCodeWriter writer,
        string modulePrefix,
        IReadOnlyList<OperationModel> models,
        string name,
        Func<OperationModel, string> typeSelector)
    {
        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.Write("Api");
        writer.Write(name);
        writer.WriteLine("ByEndpoint {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write("readonly ");
            writer.Write(models[i].Key);
            writer.Write(": ");
            writer.Write(typeSelector(models[i]));
            writer.WriteLine(";");
        }
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteResultMetadata(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.Write("export const ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiResults = {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write(models[i].Key);
            writer.WriteLine(": {");
            writer.PushIndent();
            for (var resultIndex = 0; resultIndex < models[i].Results.Length; resultIndex++)
            {
                var result = models[i].Results[resultIndex];
                writer.Write(result.MethodName);
                writer.Write(": { id: ");
                writer.Write(Quote(result.Id));
                writer.Write(", kind: ");
                writer.Write(Quote(result.Kind));
                writer.Write(", status: ");
                writer.Write(result.StatusCode.ToString(System.Globalization.CultureInfo.InvariantCulture));
                if (!string.IsNullOrWhiteSpace(result.ContentType))
                {
                    writer.Write(", contentType: ");
                    writer.Write(Quote(result.ContentType!));
                }

                writer.WriteLine(" },");
            }
            writer.PopIndent();
            writer.WriteLine("},");
        }
        writer.PopIndent();
        writer.WriteLine("} as const;");
        writer.WriteLine();
    }

    static void WriteResultBuilderInterface(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiResultBuilderByEndpoint {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write("readonly ");
            writer.Write(models[i].Key);
            writer.WriteLine(": {");
            writer.PushIndent();
            for (var resultIndex = 0; resultIndex < models[i].Results.Length; resultIndex++)
            {
                var result = models[i].Results[resultIndex];
                writer.Write("readonly ");
                writer.Write(result.MethodName);
                writer.Write(": ");
                if (result.IsVoid)
                    writer.Write("() => ApiMockResponse<void>;");
                else
                {
                    writer.Write("(body: ");
                    writer.Write(result.BodyTypeText);
                    writer.Write(") => ApiMockResponse<");
                    writer.Write(result.BodyTypeText);
                    writer.Write(">;");
                }

                writer.WriteLine();
            }
            writer.PopIndent();
            writer.WriteLine("};");
        }
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteMockTypes(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.WriteLine("export interface ApiMockResponse<TBody = unknown> {");
        writer.PushIndent();
        writer.WriteLine("readonly kind: 'response';");
        writer.WriteLine("readonly status: number;");
        writer.WriteLine("readonly body?: TBody;");
        writer.WriteLine("readonly contentType?: string;");
        writer.WriteLine("readonly headers?: Record<string, string>;");
        writer.WriteLine("readonly resultId?: string;");
        writer.WriteLine("readonly resultKind?: string;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("export interface ApiMockUnhandledResult {");
        writer.PushIndent();
        writer.WriteLine("readonly kind: 'unhandled';");
        writer.WriteLine("readonly message?: string;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("export type ApiMockResult<TBody = unknown> = ApiMockResponse<TBody> | ApiMockUnhandledResult;");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockState {");
        writer.PushIndent();
        writer.Write("readonly requests: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord[];");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockRequestRecord<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey = ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey> {");
        writer.PushIndent();
        writer.WriteLine("readonly endpointKey: TKey;");
        writer.Write("readonly endpointId: (typeof ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds)[TKey];");
        writer.Write("readonly scopePolicies: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiScopePolicyByEndpoint[TKey];");
        writer.WriteLine("readonly operationId: string;");
        writer.WriteLine("readonly method: string;");
        writer.WriteLine("readonly pathname: string;");
        writer.WriteLine("readonly search: string;");
        writer.Write("readonly route: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiRouteByEndpoint[TKey];");
        writer.Write("readonly query: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiQueryByEndpoint[TKey];");
        writer.Write("readonly body: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiBodyByEndpoint[TKey];");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockHandlerContext<TKey extends ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey> {");
        writer.PushIndent();
        writer.WriteLine("readonly request: Request;");
        writer.WriteLine("readonly endpointKey: TKey;");
        writer.Write("readonly endpointId: (typeof ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds)[TKey];");
        writer.Write("readonly scopePolicies: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiScopePolicyByEndpoint[TKey];");
        writer.Write("readonly route: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiRouteByEndpoint[TKey];");
        writer.Write("readonly query: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiQueryByEndpoint[TKey];");
        writer.Write("readonly body: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiBodyByEndpoint[TKey];");
        writer.Write("readonly result: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiResultBuilderByEndpoint[TKey];");
        writer.Write("readonly record: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<TKey>;");
        writer.Write("readonly state: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockState;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export type ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockHandler<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey> = (context: ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockHandlerContext<TKey>) => ApiMockResult<");
        writer.Write(modulePrefix);
        writer.Write("ApiResponseBodyByEndpoint[TKey]> | Promise<ApiMockResult<");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiResponseBodyByEndpoint[TKey]>>;");
        writer.WriteLine();

        writer.Write("export type ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockHandlers = Partial<{");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            writer.Write("readonly ");
            writer.Write(models[i].Key);
            writer.Write(": ");
            writer.Write(modulePrefix);
            writer.Write("ApiMockHandler<");
            writer.Write(Quote(models[i].Key));
            writer.WriteLine(">;");
        }
        writer.PopIndent();
        writer.WriteLine("}>;");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockInstallOptions {");
        writer.PushIndent();
        writer.WriteLine("readonly urlPattern: string;");
        writer.WriteLine("readonly fallbackUnhandled?: boolean;");
        writer.WriteLine("readonly unhandledStatus?: number;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("export interface ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMock {");
        writer.PushIndent();
        writer.Write("readonly state: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockState;");
        writer.Write("readonly requests: readonly ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord[];");
        writer.Write("requestsFor<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey>(endpointKey: TKey): ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<TKey>[];");
        writer.Write("requestCountFor<TKey extends ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey>(endpointKey: TKey): number;");
        writer.Write("firstRequestFor<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey>(endpointKey: TKey): ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<TKey> | undefined;");
        writer.Write("lastRequestFor<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey>(endpointKey: TKey): ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<TKey> | undefined;");
        writer.Write("clearRequests(endpointKey?: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey): void;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteResultBuilders(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.Write("const ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiResultBuilders = {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            var model = models[i];
            writer.Write(model.Key);
            writer.WriteLine(": {");
            writer.PushIndent();
            for (var resultIndex = 0; resultIndex < model.Results.Length; resultIndex++)
                WriteResultBuilderMethod(ref writer, camelPrefix, model, model.Results[resultIndex]);

            writer.PopIndent();
            writer.WriteLine("},");
        }

        writer.PopIndent();
        writer.Write("} as const satisfies ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiResultBuilderByEndpoint;");
        writer.WriteLine();
    }

    static void WriteResultBuilderMethod(
        ref PooledCodeWriter writer,
        string camelPrefix,
        OperationModel model,
        ResultModel result)
    {
        writer.Write(result.MethodName);
        if (result.IsVoid)
        {
            writer.Write(": () => semanticNoContent(");
            writer.Write(camelPrefix);
            writer.Write("ApiResults.");
            writer.Write(model.Key);
            writer.Write(".");
            writer.Write(result.MethodName);
            writer.WriteLine("),");
            return;
        }

        writer.Write(": (body: ");
        writer.Write(result.BodyTypeText);
        writer.Write(") => semanticResult(");
        writer.Write(camelPrefix);
        writer.Write("ApiResults.");
        writer.Write(model.Key);
        writer.Write(".");
        writer.Write(result.MethodName);
        writer.WriteLine(", body),");
    }

    void WriteInstallFunction(ref PooledCodeWriter writer, string modulePrefix)
    {
        writer.Write("export async function install");
        writer.Write(modulePrefix);
        writer.Write("ApiMock(page: Page, handlers: ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockHandlers, options: ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockInstallOptions): Promise<");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMock> {");
        writer.PushIndent();
        writer.Write("const state: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockState = { requests: [] };");
        writer.Write("await page.route(options.urlPattern, async (route) => handle");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiRoute(route, handlers, state, options));");
        writer.WriteLine("return {");
        writer.PushIndent();
        writer.WriteLine("state,");
        writer.WriteLine("requests: state.requests,");
        writer.WriteLine("requestsFor(endpointKey) {");
        writer.PushIndent();
        writer.Write("return state.requests.filter((request): request is ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<typeof endpointKey> => request.endpointKey === endpointKey);");
        writer.PopIndent();
        writer.WriteLine("},");
        writer.WriteLine("requestCountFor(endpointKey) {");
        writer.PushIndent();
        writer.WriteLine("return state.requests.filter((request) => request.endpointKey === endpointKey).length;");
        writer.PopIndent();
        writer.WriteLine("},");
        writer.WriteLine("firstRequestFor(endpointKey) {");
        writer.PushIndent();
        writer.Write("return state.requests.find((request): request is ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<typeof endpointKey> => request.endpointKey === endpointKey);");
        writer.PopIndent();
        writer.WriteLine("},");
        writer.WriteLine("lastRequestFor(endpointKey) {");
        writer.PushIndent();
        writer.WriteLine("for (let index = state.requests.length - 1; index >= 0; index -= 1) {");
        writer.PushIndent();
        writer.WriteLine("const request = state.requests[index];");
        writer.WriteLine("if (request.endpointKey === endpointKey) {");
        writer.PushIndent();
        writer.Write("return request as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<typeof endpointKey>;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine("return undefined;");
        writer.PopIndent();
        writer.WriteLine("},");
        writer.WriteLine("clearRequests(endpointKey) {");
        writer.PushIndent();
        writer.WriteLine("if (endpointKey === undefined) {");
        writer.PushIndent();
        writer.WriteLine("state.requests.length = 0;");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine("for (let index = state.requests.length - 1; index >= 0; index -= 1) {");
        writer.PushIndent();
        writer.WriteLine("if (state.requests[index].endpointKey === endpointKey) {");
        writer.PushIndent();
        writer.WriteLine("state.requests.splice(index, 1);");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("},");
        writer.PopIndent();
        writer.WriteLine("};");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteRouteHandler(ref PooledCodeWriter writer, string modulePrefix)
    {
        var camelPrefix = ToCamelCase(modulePrefix);
        writer.Write("async function handle");
        writer.Write(modulePrefix);
        writer.Write("ApiRoute(route: Route, handlers: ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockHandlers, state: ");
        writer.Write(modulePrefix);
        writer.Write("ApiMockState, options: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockInstallOptions) {");
        writer.PushIndent();
        writer.WriteLine("const request = route.request();");
        writer.WriteLine("const method = request.method().toUpperCase();");
        writer.WriteLine("const url = new URL(request.url());");
        writer.WriteLine("if (method === 'OPTIONS') {");
        writer.PushIndent();
        writer.WriteLine("await fulfillApiMockResponse(route, noContent(204));");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("const match = match");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpoint(method, url.pathname);");
        writer.WriteLine("if (!match) {");
        writer.PushIndent();
        writer.WriteLine("await fulfillUnhandledApiMockRequest(route, options, `Unhandled API mock request: ${method} ${url.pathname}`);");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("const body = await readApiMockRequestBody(request);");
        writer.Write("const query = decode");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiQuery(match.endpointKey, url.searchParams);");
        writer.Write("const record = {");
        writer.WriteLine();
        writer.PushIndent();
        writer.WriteLine("endpointKey: match.endpointKey,");
        writer.Write("endpointId: ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds[match.endpointKey],");
        writer.Write("operationId: ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds[match.endpointKey],");
        writer.Write("scopePolicies: ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiScopePolicies[match.endpointKey],");
        writer.WriteLine("method,");
        writer.WriteLine("pathname: url.pathname,");
        writer.WriteLine("search: url.search,");
        writer.WriteLine("route: match.route,");
        writer.WriteLine("query,");
        writer.WriteLine("body,");
        writer.PopIndent();
        writer.Write("} as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord;");
        writer.WriteLine("state.requests.push(record);");
        writer.WriteLine();

        writer.Write("const handler = handlers[match.endpointKey] as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockHandler<typeof match.endpointKey> | undefined;");
        writer.WriteLine("if (!handler) {");
        writer.PushIndent();
        writer.WriteLine("await fulfillUnhandledApiMockRequest(route, options, `Unhandled API mock handler: ${match.endpointKey}`);");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("const resultBuilder = ");
        writer.Write(ToCamelCase(modulePrefix));
        writer.WriteLine("ApiResultBuilders[match.endpointKey];");
        writer.WriteLine();

        writer.Write("const result = await handler({");
        writer.WriteLine();
        writer.PushIndent();
        writer.WriteLine("request,");
        writer.WriteLine("endpointKey: match.endpointKey,");
        writer.Write("endpointId: ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiEndpointIds[match.endpointKey],");
        writer.Write("scopePolicies: ");
        writer.Write(camelPrefix);
        writer.WriteLine("ApiScopePolicies[match.endpointKey],");
        writer.WriteLine("route: match.route,");
        writer.WriteLine("query,");
        writer.Write("body: body as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiBodyByEndpoint[typeof match.endpointKey],");
        writer.Write("result: resultBuilder as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiResultBuilderByEndpoint[typeof match.endpointKey],");
        writer.Write("record: record as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockRequestRecord<typeof match.endpointKey>,");
        writer.WriteLine("state,");
        writer.PopIndent();
        writer.WriteLine("});");
        writer.WriteLine();

        writer.WriteLine("if (result.kind === 'unhandled') {");
        writer.PushIndent();
        writer.WriteLine("await fulfillUnhandledApiMockRequest(route, options, result.message ?? `Unhandled API mock result: ${match.endpointKey}`);");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("await fulfillApiMockResponse(route, result);");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteMatcher(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        writer.Write("interface ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointMatch<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey = ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointKey> {");
        writer.PushIndent();
        writer.WriteLine("readonly endpointKey: TKey;");
        writer.Write("readonly route: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiRouteByEndpoint[TKey];");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("function match");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpoint(method: string, pathname: string): ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiEndpointMatch | null {");
        writer.PushIndent();
        var methods = models.Select(static model => model.Http.Method).Distinct(StringComparer.Ordinal).OrderBy(static value => value, StringComparer.Ordinal).ToArray();
        for (var i = 0; i < methods.Length; i++)
        {
            var method = methods[i];
            writer.Write(i == 0 ? "if" : "else if");
            writer.Write(" (method === ");
            writer.Write(Quote(method));
            writer.WriteLine(") {");
            writer.PushIndent();
            var methodModels = models
                .Where(model => string.Equals(model.Http.Method, method, StringComparison.Ordinal))
                .OrderBy(static model => model.RouteParameterCount)
                .ThenByDescending(static model => model.RouteSegmentCount)
                .ThenBy(static model => model.Key, StringComparer.Ordinal)
                .ToArray();
            for (var modelIndex = 0; modelIndex < methodModels.Length; modelIndex++)
                WriteEndpointRouteMatch(ref writer, modulePrefix, methodModels[modelIndex], modelIndex);

            writer.PopIndent();
            writer.WriteLine("}");
        }

        writer.WriteLine("return null;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteEndpointRouteMatch(ref PooledCodeWriter writer, string modulePrefix, OperationModel model, int index)
    {
        var routeVariable = $"route{index}";
        writer.Write("const ");
        writer.Write(routeVariable);
        writer.Write(" = matchApiMockRoute(");
        writer.Write(Quote(model.Http.Route));
        writer.WriteLine(", pathname);");
        writer.Write("if (");
        writer.Write(routeVariable);
        writer.WriteLine(") {");
        writer.PushIndent();
        writer.Write("return { endpointKey: ");
        writer.Write(Quote(model.Key));
        writer.Write(", route: ");
        writer.Write(routeVariable);
        writer.Write(" as ");
        writer.Write(modulePrefix);
        writer.Write("ApiRouteByEndpoint[");
        writer.Write(Quote(model.Key));
        writer.WriteLine("] };");
        writer.PopIndent();
        writer.WriteLine("}");
    }

    static void WriteDecoders(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        writer.Write("function decode");
        writer.Write(modulePrefix);
        writer.Write("ApiQuery<TKey extends ");
        writer.Write(modulePrefix);
        writer.Write("ApiEndpointKey>(endpointKey: TKey, searchParams: URLSearchParams): ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiQueryByEndpoint[TKey] {");
        writer.PushIndent();
        writer.WriteLine("switch (endpointKey) {");
        writer.PushIndent();
        for (var i = 0; i < models.Count; i++)
        {
            if (!models[i].HasQueryInput)
                continue;

            writer.Write("case ");
            writer.Write(Quote(models[i].Key));
            writer.Write(":");
            writer.WriteLine();
            writer.PushIndent();
            writer.Write("return decode");
            writer.Write(ToPascalCase(models[i].Key));
            writer.Write("Query(searchParams) as ");
            writer.Write(modulePrefix);
            writer.WriteLine("ApiQueryByEndpoint[TKey];");
            writer.PopIndent();
        }
        writer.WriteLine("default:");
        writer.PushIndent();
        writer.Write("return {} as ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiQueryByEndpoint[TKey];");
        writer.PopIndent();
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        for (var i = 0; i < models.Count; i++)
        {
            if (!models[i].HasQueryInput)
                continue;

            WriteQueryDecoder(ref writer, models[i]);
        }
    }

    static void WriteQueryDecoder(ref PooledCodeWriter writer, OperationModel model)
    {
        writer.Write("function decode");
        writer.Write(ToPascalCase(model.Key));
        writer.Write("Query(searchParams: URLSearchParams): ");
        writer.Write(model.QueryType);
        writer.WriteLine(" {");
        writer.PushIndent();
        writer.Write("const query: Partial<");
        writer.Write(model.QueryType);
        writer.WriteLine("> = {};");

        foreach (var property in model.QueryProperties)
            WriteQueryPropertyDecoder(ref writer, property);

        writer.Write("return query as ");
        writer.Write(model.QueryType);
        writer.WriteLine(";");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static void WriteQueryPropertyDecoder(ref PooledCodeWriter writer, QueryPropertyModel property)
    {
        var variableName = ToCamelCase(property.PropertyName);
        if (property.IsArray)
        {
            writer.Write("const ");
            writer.Write(variableName);
            writer.Write(" = searchParams.getAll(");
            writer.Write(Quote(property.QueryName));
            writer.WriteLine(");");
            writer.Write("if (");
            writer.Write(variableName);
            writer.WriteLine(".length > 0) {");
            writer.PushIndent();
            writer.Write("query.");
            writer.Write(property.PropertyName);
            writer.Write(" = ");
            writer.Write(variableName);
            writer.Write(".map(");
            writer.Write(GetArrayDecoderExpression(property));
            writer.Write(") as ");
            writer.Write(property.TypeText);
            writer.WriteLine(";");
            writer.PopIndent();
            writer.WriteLine("}");
            return;
        }

        writer.Write("const ");
        writer.Write(variableName);
        writer.Write(" = ");
        writer.Write(property.Decoder);
        writer.Write("(searchParams.get(");
        writer.Write(Quote(property.QueryName));
        writer.WriteLine("));");
        writer.Write("if (");
        writer.Write(variableName);
        writer.WriteLine(" !== undefined) {");
        writer.PushIndent();
        writer.Write("query.");
        writer.Write(property.PropertyName);
        writer.Write(" = ");
        writer.Write(variableName);
        writer.Write(" as ");
        writer.Write(property.TypeText);
        writer.WriteLine(";");
        writer.PopIndent();
        writer.WriteLine("}");
    }

    static void WriteRuntimeHelpers(ref PooledCodeWriter writer, string modulePrefix, IReadOnlyList<OperationModel> models)
    {
        var hasBodyResults = models.Any(static model => model.Results.Any(static result => !result.IsVoid));
        var hasVoidResults = models.Any(static model => model.Results.Any(static result => result.IsVoid));

        writer.WriteLine("interface ApiMockResultMetadata {");
        writer.PushIndent();
        writer.WriteLine("readonly id: string;");
        writer.WriteLine("readonly kind: string;");
        writer.WriteLine("readonly status: number;");
        writer.WriteLine("readonly contentType?: string;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        if (hasBodyResults)
        {
            writer.WriteLine("function semanticResult<TBody>(metadata: ApiMockResultMetadata, body: TBody): ApiMockResponse<TBody> {");
            writer.PushIndent();
            writer.WriteLine("return {");
            writer.PushIndent();
            writer.WriteLine("body,");
            writer.WriteLine("contentType: metadata.contentType,");
            writer.WriteLine("kind: 'response',");
            writer.WriteLine("resultId: metadata.id,");
            writer.WriteLine("resultKind: metadata.kind,");
            writer.WriteLine("status: metadata.status,");
            writer.PopIndent();
            writer.WriteLine("};");
            writer.PopIndent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        if (hasVoidResults)
        {
            writer.WriteLine("function semanticNoContent(metadata: ApiMockResultMetadata): ApiMockResponse<void> {");
            writer.PushIndent();
            writer.WriteLine("return {");
            writer.PushIndent();
            writer.WriteLine("contentType: metadata.contentType,");
            writer.WriteLine("kind: 'response',");
            writer.WriteLine("resultId: metadata.id,");
            writer.WriteLine("resultKind: metadata.kind,");
            writer.WriteLine("status: metadata.status,");
            writer.PopIndent();
            writer.WriteLine("};");
            writer.PopIndent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        writer.WriteLine("export function ok<TBody>(body: TBody): ApiMockResponse<TBody> {");
        writer.PushIndent();
        writer.WriteLine("return status(200, body);");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("export function status<TBody>(statusCode: number, body: TBody, headers?: Record<string, string>): ApiMockResponse<TBody> {");
        writer.PushIndent();
        writer.WriteLine("return { body, headers, kind: 'response', status: statusCode };");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("export function noContent(statusCode = 204): ApiMockResponse<void> {");
        writer.PushIndent();
        writer.WriteLine("return { kind: 'response', status: statusCode };");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("export function unhandled(message?: string): ApiMockUnhandledResult {");
        writer.PushIndent();
        writer.WriteLine("return message === undefined ? { kind: 'unhandled' } : { kind: 'unhandled', message };");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("async function fulfillApiMockResponse(route: Route, response: ApiMockResponse) {");
        writer.PushIndent();
        writer.WriteLine("const headers = {");
        writer.PushIndent();
        writer.WriteLine("'access-control-allow-headers': 'authorization,content-type',");
        writer.WriteLine("'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',");
        writer.WriteLine("'access-control-allow-origin': '*',");
        writer.WriteLine("'access-control-expose-headers': 'x-cohesive-result-id,x-cohesive-result-kind',");
        writer.WriteLine("...(response.resultId === undefined ? {} : { 'x-cohesive-result-id': response.resultId }),");
        writer.WriteLine("...(response.resultKind === undefined ? {} : { 'x-cohesive-result-kind': response.resultKind }),");
        writer.WriteLine("...(response.headers ?? {}),");
        writer.PopIndent();
        writer.WriteLine("};");
        writer.WriteLine("if (response.body === undefined) {");
        writer.PushIndent();
        writer.WriteLine("await route.fulfill({ headers, status: response.status });");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("await route.fulfill({");
        writer.PushIndent();
        writer.WriteLine("body: JSON.stringify(response.body),");
        writer.WriteLine("contentType: response.contentType ?? 'application/json',");
        writer.WriteLine("headers,");
        writer.WriteLine("status: response.status,");
        writer.PopIndent();
        writer.WriteLine("});");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.Write("async function fulfillUnhandledApiMockRequest(route: Route, options: ");
        writer.Write(modulePrefix);
        writer.WriteLine("ApiMockInstallOptions, message: string) {");
        writer.PushIndent();
        writer.WriteLine("if (options.fallbackUnhandled) {");
        writer.PushIndent();
        writer.WriteLine("await route.fallback();");
        writer.WriteLine("return;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("await fulfillApiMockResponse(route, status(options.unhandledStatus ?? 501, { message }));");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("async function readApiMockRequestBody(request: Request): Promise<unknown> {");
        writer.PushIndent();
        writer.WriteLine("const text = request.postData();");
        writer.WriteLine("if (!text) {");
        writer.PushIndent();
        writer.WriteLine("return null;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("try {");
        writer.PushIndent();
        writer.WriteLine("return JSON.parse(text) as unknown;");
        writer.PopIndent();
        writer.WriteLine("} catch {");
        writer.PushIndent();
        writer.WriteLine("return text;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function matchApiMockRoute(template: string, pathname: string): Record<string, string> | null {");
        writer.PushIndent();
        writer.WriteLine("const templateSegments = splitApiMockPath(template);");
        writer.WriteLine("const pathSegments = splitApiMockPath(pathname);");
        writer.WriteLine("if (templateSegments.length !== pathSegments.length) {");
        writer.PushIndent();
        writer.WriteLine("return null;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("const values: Record<string, string> = {};");
        writer.WriteLine("for (let index = 0; index < templateSegments.length; index += 1) {");
        writer.PushIndent();
        writer.WriteLine("const templateSegment = templateSegments[index];");
        writer.WriteLine("const pathSegment = pathSegments[index];");
        writer.WriteLine("const parameterName = readApiMockRouteParameter(templateSegment);");
        writer.WriteLine("if (parameterName) {");
        writer.PushIndent();
        writer.WriteLine("values[parameterName] = decodeURIComponent(pathSegment);");
        writer.WriteLine("continue;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("if (templateSegment !== pathSegment) {");
        writer.PushIndent();
        writer.WriteLine("return null;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return values;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function splitApiMockPath(path: string): string[] {");
        writer.PushIndent();
        writer.WriteLine("return path.split('/').filter((segment) => segment.length > 0);");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function readApiMockRouteParameter(segment: string): string | null {");
        writer.PushIndent();
        writer.WriteLine("if (!segment.startsWith('{') || !segment.endsWith('}')) {");
        writer.PushIndent();
        writer.WriteLine("return null;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("const token = segment.slice(1, -1);");
        writer.WriteLine("const separatorIndex = token.search(/[:=?]/);");
        writer.WriteLine("return separatorIndex >= 0 ? token.slice(0, separatorIndex) : token;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function readApiMockString(value: string | null): string | undefined {");
        writer.PushIndent();
        writer.WriteLine("return value === null ? undefined : value;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function readApiMockNumber(value: string | null): number | undefined {");
        writer.PushIndent();
        writer.WriteLine("if (value === null) {");
        writer.PushIndent();
        writer.WriteLine("return undefined;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("const parsed = Number(value);");
        writer.WriteLine("return Number.isFinite(parsed) ? parsed : undefined;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("function readApiMockBoolean(value: string | null): boolean | undefined {");
        writer.PushIndent();
        writer.WriteLine("if (value === null) {");
        writer.PushIndent();
        writer.WriteLine("return undefined;");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return value.toLocaleLowerCase() === 'true';");
        writer.PopIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    static ImmutableArray<OperationModel> BuildOperationModels(ApiDefinition definition)
    {
        var usedKeys = new HashSet<string>(StringComparer.Ordinal);
        var models = ImmutableArray.CreateBuilder<OperationModel>(definition.Operations.Count);
        for (var i = 0; i < definition.Operations.Count; i++)
        {
            var operation = definition.Operations[i];
            if (operation.Http is not { } http)
                continue;

            models.Add(new OperationModel(
                Operation: operation,
                Http: http,
                Key: CreateUniqueOperationKey(operation, usedKeys),
                RouteType: BuildRouteType(http),
                QueryType: BuildQueryType(http),
                BodyType: http.Body is { } body ? GetTypeScriptTypeText(body.BodyType) : "null",
                ResponseBodyType: BuildResponseBodyType(operation),
                Results: BuildResultModels(operation),
                QueryProperties: BuildQueryProperties(http),
                RouteParameterCount: CountRouteParameters(http.Route),
                RouteSegmentCount: CountRouteSegments(http.Route)));
        }

        return models.ToImmutable();
    }

    static string CreateUniqueOperationKey(ApiOperation operation, HashSet<string> usedKeys)
    {
        var baseKey = CreateOperationKey(operation);
        var key = baseKey;
        var suffix = 2;
        while (!usedKeys.Add(key))
        {
            key = $"{baseKey}{suffix}";
            suffix++;
        }

        return key;
    }

    static string CreateOperationKey(ApiOperation operation)
    {
        if (operation.Entity is not { } entity)
            return ToCamelCase(SanitizeIdentifier(operation.Name, pascalCase: true));

        var entityName = StripEntitySuffix(entity.Value);
        var operationName = operation.Name;
        if (string.Equals(operationName, "Query", StringComparison.OrdinalIgnoreCase))
            return $"query{Pluralize(entityName)}";
        if (string.Equals(operationName, "Get", StringComparison.OrdinalIgnoreCase)
            || string.Equals(operationName, "Create", StringComparison.OrdinalIgnoreCase)
            || string.Equals(operationName, "Revise", StringComparison.OrdinalIgnoreCase)
            || string.Equals(operationName, "Archive", StringComparison.OrdinalIgnoreCase)
            || string.Equals(operationName, "Validate", StringComparison.OrdinalIgnoreCase))
        {
            return $"{ToCamelCase(operationName)}{entityName}";
        }

        if (operationName.StartsWith("Validate", StringComparison.Ordinal))
            return $"{ToCamelCase(operationName)}{entityName}";

        if (operationName.Contains(entityName, StringComparison.OrdinalIgnoreCase))
            return ToCamelCase(SanitizeIdentifier(operationName, pascalCase: true));

        return $"{ToCamelCase(operationName)}{entityName}";
    }

    static string BuildRouteType(HttpBinding http)
    {
        var routeParameters = http.Parameters.Where(static parameter => parameter.Source == HttpParameterSource.Route).ToArray();
        if (routeParameters.Length == 0)
            return "Record<string, never>";

        var builder = new StringBuilder("{ ");
        for (var i = 0; i < routeParameters.Length; i++)
        {
            if (i > 0)
                builder.Append(' ');

            builder.Append("readonly ");
            builder.Append(ToCamelCase(routeParameters[i].Name));
            builder.Append(": ");
            builder.Append(GetTypeScriptTypeText(routeParameters[i].Type));
            builder.Append(';');
        }

        builder.Append(" }");
        return builder.ToString();
    }

    static string BuildQueryType(HttpBinding http)
    {
        if (http.Query is { } query)
            return GetTypeScriptTypeText(query.QueryType);

        var queryParameters = http.Parameters.Where(static parameter => parameter.Source == HttpParameterSource.Query).ToArray();
        if (queryParameters.Length == 0)
            return "Record<string, never>";

        var builder = new StringBuilder("{ ");
        for (var i = 0; i < queryParameters.Length; i++)
        {
            if (i > 0)
                builder.Append(' ');

            var parameter = queryParameters[i];
            builder.Append("readonly ");
            builder.Append(ToCamelCase(parameter.Name));
            if (parameter.IsOptional || CanSkipWhenUndefined(parameter.Type))
                builder.Append('?');

            builder.Append(": ");
            builder.Append(GetTypeScriptTypeText(parameter.Type));
            builder.Append(';');
        }

        builder.Append(" }");
        return builder.ToString();
    }

    static string BuildResponseBodyType(ApiOperation operation)
    {
        var types = operation.Results
            .Select(static result => GetTypeScriptTypeText(result.BodyType))
            .Distinct(StringComparer.Ordinal)
            .ToArray();

        return types.Length == 0 ? "void" : string.Join(" | ", types);
    }

    static ImmutableArray<ResultModel> BuildResultModels(ApiOperation operation)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var results = ImmutableArray.CreateBuilder<ResultModel>(operation.Results.Count);
        for (var i = 0; i < operation.Results.Count; i++)
        {
            var result = operation.Results[i];
            results.Add(new ResultModel(
                Id: result.Id,
                Kind: ApiWireNames.ResultKind(result.Kind),
                MethodName: CreateUniqueResultMethodName(result.Id, usedNames),
                BodyTypeText: GetTypeScriptTypeText(result.BodyType),
                StatusCode: result.Http?.StatusCode ?? DefaultMockStatusCode(result.Kind, result.BodyType),
                ContentType: result.Http?.ContentType,
                IsVoid: result.BodyType == typeof(void)));
        }

        return results.ToImmutable();
    }

    static string CreateUniqueResultMethodName(string resultId, HashSet<string> usedNames)
    {
        var baseName = ToCamelCase(resultId);
        var name = baseName;
        var suffix = 2;
        while (!usedNames.Add(name))
        {
            name = $"{baseName}{suffix}";
            suffix++;
        }

        return name;
    }

    static int DefaultMockStatusCode(ApiResultKind kind, Type bodyType) =>
        kind switch
        {
            ApiResultKind.Success when bodyType == typeof(void) => 204,
            ApiResultKind.Success => 200,
            ApiResultKind.Created => 201,
            ApiResultKind.Accepted => 202,
            ApiResultKind.NoContent => 204,
            ApiResultKind.ValidationFailed => 400,
            ApiResultKind.Unauthorized => 401,
            ApiResultKind.Forbidden => 403,
            ApiResultKind.NotFound => 404,
            ApiResultKind.Conflict => 409,
            ApiResultKind.PreconditionFailed => 412,
            ApiResultKind.RateLimited => 429,
            ApiResultKind.DomainError => 422,
            ApiResultKind.InfrastructureError => 500,
            _ => bodyType == typeof(void) ? 204 : 200
        };

    static ImmutableArray<QueryPropertyModel> BuildQueryProperties(HttpBinding http)
    {
        var properties = ImmutableArray.CreateBuilder<QueryPropertyModel>();
        if (http.Query is { } query)
        {
            var queryTypeText = GetTypeScriptTypeText(query.QueryType);
            var metadata = ShapeTypeInspector.GetReadablePropertyMetadata(query.QueryType);
            for (var i = 0; i < metadata.Length; i++)
            {
                var property = metadata[i].Property;
                properties.Add(new QueryPropertyModel(
                    PropertyName: property.Name,
                    QueryName: ResolveQueryParameterName(property),
                    TypeText: $"{queryTypeText}['{property.Name}']",
                    Decoder: GetQueryDecoderName(property.PropertyType),
                    IsArray: IsSequenceType(property.PropertyType)));
            }
        }

        for (var i = 0; i < http.Parameters.Count; i++)
        {
            var parameter = http.Parameters[i];
            if (parameter.Source != HttpParameterSource.Query)
                continue;

            properties.Add(new QueryPropertyModel(
                PropertyName: ToCamelCase(parameter.Name),
                QueryName: parameter.Name,
                TypeText: GetTypeScriptTypeText(parameter.Type),
                Decoder: GetQueryDecoderName(parameter.Type),
                IsArray: IsSequenceType(parameter.Type)));
        }

        return properties.ToImmutable();
    }

    static ImmutableArray<string> CollectTypeImports(IReadOnlyList<OperationModel> models)
    {
        var names = new List<string>();
        for (var i = 0; i < models.Count; i++)
        {
            var operation = models[i].Operation;
            var http = models[i].Http;
            AppendTypeImports(names, http.Body?.BodyType);
            AppendTypeImports(names, http.Query?.QueryType);

            for (var parameterIndex = 0; parameterIndex < http.Parameters.Count; parameterIndex++)
                AppendTypeImports(names, http.Parameters[parameterIndex].Type);

            for (var resultIndex = 0; resultIndex < operation.Results.Count; resultIndex++)
                AppendTypeImports(names, operation.Results[resultIndex].BodyType);
        }

        names.Sort(StringComparer.Ordinal);
        return [.. names];
    }

    static void AppendTypeImports(List<string> names, Type? type)
    {
        if (type is null)
            return;

        var elementType = UnwrapType(type);
        if (IsBuiltInType(elementType))
            return;

        var name = GetTypeName(elementType);
        if (!names.Contains(name, StringComparer.Ordinal))
            names.Add(name);
    }

    static string GetTypeScriptTypeText(Type type)
    {
        if (type == typeof(void))
            return "void";

        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null)
            return $"{GetTypeScriptTypeText(nullable)} | null";

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateOnly) || type == typeof(TimeOnly)
            || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(char))
        {
            return "string";
        }

        if (type == typeof(bool))
            return "boolean";

        if (IsNumeric(type))
            return "number";

        if (type.IsEnum)
            return GetTypeName(type);

        if (type.IsArray)
            return $"{GetTypeScriptTypeText(type.GetElementType()!)}[]";

        if (TryGetSequenceElementType(type, out var elementType))
            return $"{GetTypeScriptTypeText(elementType!)}[]";

        return GetTypeName(type);
    }

    static string GetQueryDecoderName(Type type)
    {
        var unwrapped = UnwrapType(type);
        if (IsSequenceType(unwrapped) && TryGetSequenceElementType(unwrapped, out var elementType))
            unwrapped = UnwrapType(elementType!);

        if (unwrapped == typeof(bool))
            return "readApiMockBoolean";

        if (IsNumeric(unwrapped) || unwrapped.IsEnum)
            return "readApiMockNumber";

        return "readApiMockString";
    }

    static string GetArrayDecoderExpression(QueryPropertyModel property) =>
        property.Decoder switch
        {
            "readApiMockBoolean" => "(value) => readApiMockBoolean(value) ?? false",
            "readApiMockNumber" => "(value) => readApiMockNumber(value) ?? 0",
            _ => "(value) => readApiMockString(value) ?? ''"
        };

    static Type UnwrapType(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null)
            return UnwrapType(nullable);

        if (type.IsArray)
            return UnwrapType(type.GetElementType()!);

        if (TryGetSequenceElementType(type, out var elementType))
            return UnwrapType(elementType!);

        return type;
    }

    static bool IsBuiltInType(Type type)
    {
        if (type == typeof(void)
            || type == typeof(string)
            || type == typeof(Guid)
            || type == typeof(DateOnly)
            || type == typeof(TimeOnly)
            || type == typeof(DateTime)
            || type == typeof(DateTimeOffset)
            || type == typeof(char)
            || type == typeof(bool))
        {
            return true;
        }

        return IsNumeric(type);
    }

    static bool IsNumeric(Type type) =>
        type == typeof(byte)
        || type == typeof(sbyte)
        || type == typeof(short)
        || type == typeof(ushort)
        || type == typeof(int)
        || type == typeof(uint)
        || type == typeof(long)
        || type == typeof(ulong)
        || type == typeof(float)
        || type == typeof(double)
        || type == typeof(decimal);

    static bool IsSequenceType(Type type) =>
        type != typeof(string) && TryGetSequenceElementType(type, out _);

    static bool TryGetSequenceElementType(Type type, out Type? elementType)
    {
        if (type == typeof(string))
        {
            elementType = null;
            return false;
        }

        if (type.IsArray)
        {
            elementType = type.GetElementType();
            return elementType is not null;
        }

        var interfaces = type.GetInterfaces();
        for (var i = 0; i < interfaces.Length; i++)
        {
            var candidate = interfaces[i];
            if (!candidate.IsGenericType || candidate.GetGenericTypeDefinition() != typeof(IEnumerable<>))
                continue;

            elementType = candidate.GetGenericArguments()[0];
            return true;
        }

        elementType = null;
        return false;
    }

    static bool CanSkipWhenUndefined(Type type) =>
        Nullable.GetUnderlyingType(type) is not null || !type.IsValueType;

    static string ResolveQueryParameterName(PropertyInfo property) =>
        property.GetCustomAttribute<JsonPropertyNameAttribute>(inherit: true)?.Name ?? ToSnakeCase(property.Name);

    static int CountRouteParameters(string route)
    {
        var count = 0;
        for (var i = 0; i < route.Length; i++)
        {
            if (route[i] == '{')
                count++;
        }

        return count;
    }

    static int CountRouteSegments(string route) =>
        route.Split('/', StringSplitOptions.RemoveEmptyEntries).Length;

    static string StripEntitySuffix(string value)
    {
        foreach (var suffix in new[] { "Resource", "Dto", "Entity", "Record" })
        {
            if (value.EndsWith(suffix, StringComparison.Ordinal) && value.Length > suffix.Length)
                return value[..^suffix.Length];
        }

        return value;
    }

    static string Pluralize(string value)
    {
        if (value.EndsWith("y", StringComparison.OrdinalIgnoreCase) && value.Length > 1 && !IsVowel(value[^2]))
            return $"{value[..^1]}ies";
        if (value.EndsWith("s", StringComparison.OrdinalIgnoreCase)
            || value.EndsWith("x", StringComparison.OrdinalIgnoreCase)
            || value.EndsWith("z", StringComparison.OrdinalIgnoreCase)
            || value.EndsWith("ch", StringComparison.OrdinalIgnoreCase)
            || value.EndsWith("sh", StringComparison.OrdinalIgnoreCase))
        {
            return $"{value}es";
        }

        return $"{value}s";
    }

    static bool IsVowel(char value) => char.ToLowerInvariant(value) is 'a' or 'e' or 'i' or 'o' or 'u';

    static string ToSnakeCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return value;

        var builder = new StringBuilder(value.Length + 8);
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (char.IsUpper(current))
            {
                if (i > 0 && (char.IsLower(value[i - 1]) || char.IsDigit(value[i - 1])
                              || (i + 1 < value.Length && char.IsLower(value[i + 1]))))
                {
                    builder.Append('_');
                }

                builder.Append(char.ToLowerInvariant(current));
                continue;
            }

            builder.Append(current);
        }

        return builder.ToString();
    }

    static string ToPascalCase(string value) => SanitizeIdentifier(value, pascalCase: true);

    static string ToCamelCase(string value)
    {
        var pascal = SanitizeIdentifier(value, pascalCase: true);
        return pascal.Length == 1
            ? char.ToLowerInvariant(pascal[0]).ToString()
            : char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    static string SanitizeIdentifier(string value, bool pascalCase)
    {
        if (string.IsNullOrWhiteSpace(value))
            return pascalCase ? "Value" : "value";

        var builder = new StringBuilder(value.Length);
        var upperNext = pascalCase;
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            if (!char.IsLetterOrDigit(current))
            {
                upperNext = true;
                continue;
            }

            if (builder.Length == 0 && char.IsDigit(current))
                builder.Append('_');

            builder.Append(upperNext ? char.ToUpperInvariant(current) : current);
            upperNext = false;
        }

        if (builder.Length == 0)
            return pascalCase ? "Value" : "value";

        return builder.ToString();
    }

    static string GetTypeName(Type type)
    {
        var name = type.Name;
        var genericTick = name.IndexOf('`');
        return genericTick >= 0 ? name[..genericTick] : name;
    }

    static string Quote(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('\'');
        for (var i = 0; i < value.Length; i++)
        {
            var current = value[i];
            switch (current)
            {
                case '\'':
                    builder.Append("\\'");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    builder.Append(current);
                    break;
            }
        }

        builder.Append('\'');
        return builder.ToString();
    }

    static int EstimateInitialCapacity(ApiDefinition definition) =>
        4096 + (definition.Operations.Count * 900);

    sealed record OperationModel(
        ApiOperation Operation,
        HttpBinding Http,
        string Key,
        string RouteType,
        string QueryType,
        string BodyType,
        string ResponseBodyType,
        ImmutableArray<ResultModel> Results,
        ImmutableArray<QueryPropertyModel> QueryProperties,
        int RouteParameterCount,
        int RouteSegmentCount)
    {
        public bool HasQueryInput => QueryProperties.Length > 0;
    }

    sealed record QueryPropertyModel(
        string PropertyName,
        string QueryName,
        string TypeText,
        string Decoder,
        bool IsArray);

    sealed record ResultModel(
        string Id,
        string Kind,
        string MethodName,
        string BodyTypeText,
        int StatusCode,
        string? ContentType,
        bool IsVoid);
}
