using Cohesive.Adapters.TypeScript.Ast;
using Cohesive.Api;
using Cohesive.Api.CodeGen;
using Cohesive.CodeGen;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Emits TypeScript API client functions from <see cref="ApiDefinition"/>.
/// </summary>
public sealed class TypeScriptApiClientEmitter : IApiCodeEmitter
{
    readonly TypeScriptApiClientEmitterOptions options;

    /// <summary>
    /// Creates the emitter.
    /// </summary>
    public TypeScriptApiClientEmitter(TypeScriptApiClientEmitterOptions? options = null)
    {
        this.options = options ?? new TypeScriptApiClientEmitterOptions();
    }

    /// <inheritdoc />
    public string Language => "typescript";

    /// <inheritdoc />
    public CodeEmission Emit(in ApiCodeGenerationRequest request)
    {
        var document = new TypeScriptApiClientAstBuilder(request.Definition, options).Build();
        var writer = new PooledCodeWriter(
            initialCapacity: EstimateInitialCapacity(request.Definition),
            indentSize: options.IndentSize,
            newLine: options.NewLine);

        try
        {
            if (options.EmitAutoGeneratedHeader)
            {
                writer.WriteLine("/* <auto-generated/> */");
                writer.WriteLine();
            }

            TypeScriptSyntaxEmitter.WriteDocument(document, ref writer);
            return new CodeEmission(
                language: Language,
                documents: [new GeneratedCodeDocument(options.FileName, writer.ToString())]);
        }
        finally
        {
            writer.Dispose();
        }
    }

    /// <summary>
    /// Emits a definition directly.
    /// </summary>
    public CodeEmission Emit(ApiDefinition definition) => Emit(new ApiCodeGenerationRequest(definition));

    static int EstimateInitialCapacity(ApiDefinition definition)
    {
        var estimate = 256;
        for (var i = 0; i < definition.Operations.Count; i++)
        {
            var operation = definition.Operations[i];
            if (operation.Http is not { } http)
                continue;

            estimate += operation.Name.Length * 2;
            estimate += http.Route.Length * 2;
            estimate += http.Parameters.Count * 32;
        }

        return estimate;
    }
}
