namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Options for TypeScript Playwright API mock host emission.
/// </summary>
public sealed record TypeScriptPlaywrightApiMockEmitterOptions
{
    /// <summary>
    /// Output file name.
    /// </summary>
    public string FileName { get; init; } = "api.playwright.generated.ts";

    /// <summary>
    /// Relative import path for generated shape types.
    /// </summary>
    public string ShapesImportPath { get; init; } = "./contracts.shapes.generated";

    /// <summary>
    /// Logical module name used in exported mock host names.
    /// </summary>
    public string ModuleName { get; init; } = "api";

    /// <summary>
    /// Emitted newline sequence.
    /// </summary>
    public string NewLine { get; init; } = "\n";

    /// <summary>
    /// Indentation size in spaces.
    /// </summary>
    public int IndentSize { get; init; } = 2;

    /// <summary>
    /// Emits an auto-generated header when true.
    /// </summary>
    public bool EmitAutoGeneratedHeader { get; init; } = true;
}
