using System.Collections.Immutable;
using Cohesive.CodeGen;
using Cohesive.Model;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Emits TypeScript declarations from a shape graph.
/// </summary>
public sealed class TypeScriptShapeEmitter : IShapeCodeEmitter
{
    readonly TypeScriptEmitterOptions options;

    /// <summary>
    /// Creates a TypeScript emitter.
    /// </summary>
    public TypeScriptShapeEmitter(TypeScriptEmitterOptions? options = null)
    {
        this.options = options ?? new TypeScriptEmitterOptions();
    }

    /// <inheritdoc />
    public string Language => "typescript";

    /// <inheritdoc />
    public CodeEmission Emit(in ShapeCodeGenerationRequest request)
    {
        var document = new TypeScriptShapeAstBuilder(request.Graph, options.ExternalTypeModules).Build();
        var writer = new PooledCodeWriter(
            initialCapacity: EstimateInitialCapacity(request.Graph),
            indentSize: options.IndentSize,
            newLine: options.NewLine);

        try
        {
            if (options.EmitAutoGeneratedHeader)
            {
                writer.WriteLine("/* <auto-generated/> */");
                writer.WriteLine();
            }

            TypeScriptSyntaxEmitter.WriteDocument(document, ref writer);
            return new CodeEmission(
                language: Language,
                documents: [new GeneratedCodeDocument(options.FileName, writer.ToString())]);
        }
        finally
        {
            writer.Dispose();
        }
    }

    /// <summary>
    /// Emits a complete graph directly.
    /// </summary>
    public CodeEmission Emit(ShapeGraph graph) => Emit(new ShapeCodeGenerationRequest(graph));

    /// <summary>
    /// Emits a single shape with optional named-type dependencies.
    /// </summary>
    public CodeEmission Emit(
        Shape shape,
        ImmutableArray<TypeDefinition> namedTypes = default,
        GraphId? graphId = null)
    {
        return Emit(ShapeCodeGenerationRequest.FromShape(shape, namedTypes, graphId));
    }

    static int EstimateInitialCapacity(ShapeGraph graph)
    {
        var estimate = 256;
        for (var i = 0; i < graph.Shapes.Length; i++)
        {
            estimate += graph.Shapes[i].Id.Value.Length;
            estimate += graph.Shapes[i].Fields.Length * 40;
        }

        for (var i = 0; i < graph.NamedTypes.Length; i++)
        {
            estimate += graph.NamedTypes[i].Id.Value.Length;
            estimate += 64;
        }

        return estimate;
    }
}
