using System.Collections.Immutable;
using System.Globalization;
using System.Text.Json;
using Cohesive.CodeGen;

namespace Cohesive.Adapters.TypeScript;

/// <summary>
/// Emits TypeScript constant objects from target-neutral contract constants.
/// </summary>
public sealed class TypeScriptContractConstantsEmitter
{
    readonly TypeScriptEmitterOptions options;

    /// <summary>
    /// Creates the emitter.
    /// </summary>
    public TypeScriptContractConstantsEmitter(TypeScriptEmitterOptions? options = null)
    {
        this.options = options ?? new TypeScriptEmitterOptions();
    }

    /// <summary>
    /// Output language identifier.
    /// </summary>
    public string Language => "typescript";

    /// <summary>
    /// Emits a TypeScript constants document.
    /// </summary>
    public CodeEmission Emit(ContractConstantSet constants)
    {
        ArgumentNullException.ThrowIfNull(constants);

        var writer = new PooledCodeWriter(
            initialCapacity: EstimateInitialCapacity(constants),
            indentSize: options.IndentSize,
            newLine: options.NewLine);

        try
        {
            if (options.EmitAutoGeneratedHeader)
            {
                writer.WriteLine("/* <auto-generated/> */");
                writer.WriteLine();
            }

            WriteConstants(constants.Groups, ref writer);
            return new CodeEmission(
                language: Language,
                documents: [new GeneratedCodeDocument(options.FileName, writer.ToString())]);
        }
        finally
        {
            writer.Dispose();
        }
    }

    static void WriteConstants(ImmutableArray<ContractConstantGroup> groups, ref PooledCodeWriter writer)
    {
        for (var i = 0; i < groups.Length; i++)
        {
            if (i > 0)
                writer.WriteLine();

            WriteGroup(groups[i], ref writer);
        }
    }

    static void WriteGroup(ContractConstantGroup group, ref PooledCodeWriter writer)
    {
        writer.Write("export const ");
        writer.Write(ToCamelCase(group.Name));
        writer.WriteLine(" = {");
        writer.PushIndent();

        var constants = group.Constants;
        for (var i = 0; i < constants.Length; i++)
        {
            var constant = constants[i];
            writer.Write(ToCamelCase(constant.Name));
            writer.Write(": ");
            writer.Write(FormatLiteral(constant.Value));
            writer.WriteLine(",");
        }

        writer.PopIndent();
        writer.WriteLine("} as const");
    }

    static string FormatLiteral(object value) =>
        value switch
        {
            string text => FormatStringLiteral(text),
            char character => FormatStringLiteral(character.ToString()),
            bool flag => flag ? "true" : "false",
            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
            _ => JsonSerializer.Serialize(value)
        };

    static string FormatStringLiteral(string value)
    {
        var json = JsonSerializer.Serialize(value);
        var inner = json[1..^1]
            .Replace("'", "\\'", StringComparison.Ordinal)
            .Replace("\\\"", "\"", StringComparison.Ordinal);
        return $"'{inner}'";
    }

    static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        if (!char.IsUpper(value[0]))
            return value;

        var chars = value.ToCharArray();
        var leadingUpperCount = 1;
        while (leadingUpperCount < chars.Length && char.IsUpper(chars[leadingUpperCount]))
            leadingUpperCount++;

        if (leadingUpperCount == chars.Length)
        {
            for (var i = 0; i < chars.Length; i++)
                chars[i] = char.ToLowerInvariant(chars[i]);

            return new string(chars);
        }

        var charsToLower = leadingUpperCount == 1 ? 1 : leadingUpperCount - 1;
        for (var i = 0; i < charsToLower; i++)
            chars[i] = char.ToLowerInvariant(chars[i]);

        return new string(chars);
    }

    static int EstimateInitialCapacity(ContractConstantSet constants)
    {
        var estimate = 128;
        var groups = constants.Groups;
        for (var i = 0; i < groups.Length; i++)
        {
            estimate += groups[i].Name.Length + 32;
            var groupConstants = groups[i].Constants;
            for (var j = 0; j < groupConstants.Length; j++)
            {
                var valueTextLength = Convert.ToString(groupConstants[j].Value, CultureInfo.InvariantCulture)?.Length ?? 16;
                estimate += groupConstants[j].Name.Length + valueTextLength + 16;
            }
        }

        return estimate;
    }
}
