<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cohesive.Api\Cohesive.Api.csproj" />
    <ProjectReference Include="..\..\Cohesive.Identity\Cohesive.Identity.csproj" />
    <ProjectReference Include="..\..\Cohesive\Cohesive.csproj" />
    <ProjectReference Include="..\..\Cohesive.Host\Cohesive.Host.csproj" />
    <ProjectReference Include="..\..\Cohesive.Storage\Cohesive.Storage.csproj" />
  </ItemGroup>

</Project>
