using Cohesive.Adapters.CSharp;
using Cohesive.Model;
using Cohesive.Relations.Model;
using Cohesive.Relations.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Cohesive.Tests.CodeGen;

public sealed class CSharpRelationshipCatalogEmitterTests
{
    [Fact]
    public void Emit_LoadRelationships_ProducesExactStronglyTypedGoldenSource()
    {
        var catalog = CreateLoadCatalog();
        var emitter = new CSharpRelationshipCatalogEmitter(new()
        {
            Namespace = "Cohesive.Generated",
            RootClassName = "DomainRelationships",
            FileName = "DomainRelationships.g.cs",
            NewLine = "\n",
            EmitAutoGeneratedHeader = true
        });

        var result = emitter.Emit(catalog);

        Assert.True(result.Succeeded);
        Assert.True(result.Validation.IsValid);
        Assert.Empty(result.Diagnostics);
        Assert.Equal(RelationshipCatalogFingerprinter.Compute(catalog), result.CatalogFingerprint);

        var emission = Assert.IsType<Cohesive.CodeGen.CodeEmission>(result.Emission);
        Assert.Equal("csharp", emission.Language);
        var document = Assert.Single(emission.Documents);
        Assert.Equal("DomainRelationships.g.cs", document.FileName);

        const string expected = """
            // <auto-generated/>

            namespace Cohesive.Generated;

            /// <summary>Canonical semantic relationship identifiers generated from a relationship catalog.</summary>
            public static class DomainRelationships
            {
                /// <summary>Relationship identifiers originating from one canonical source shape.</summary>
                public static class Load
                {
                    /// <summary>Canonical semantic relationship identifier.</summary>
                    public static readonly global::Cohesive.Relations.Model.RelationshipId Customer = new("domain.load.customer");
                    /// <summary>Canonical semantic relationship identifier.</summary>
                    public static readonly global::Cohesive.Relations.Model.RelationshipId Equipment = new("domain.load.equipment");
                }
            }
            """;

        Assert.Equal(expected + "\n", document.Text);
        Assert.Contains("DomainRelationships", document.Text, StringComparison.Ordinal);
        Assert.Contains("public static class Load", document.Text, StringComparison.Ordinal);
        Assert.Contains("RelationshipId Customer", document.Text, StringComparison.Ordinal);
        Assert.Contains("RelationshipId Equipment", document.Text, StringComparison.Ordinal);
        AssertCompiles(document.Text);
    }

    [Fact]
    public void Emit_ReorderedDeclarations_ProducesIdenticalFingerprintAndSource()
    {
        var relationships = CreateLoadCatalog().Relationships;
        var first = new RelationshipCatalog([relationships[1], relationships[0]]);
        var second = new RelationshipCatalog([relationships[0], relationships[1]]);
        var emitter = new CSharpRelationshipCatalogEmitter(new()
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        });

        var firstResult = emitter.Emit(first);
        var secondResult = emitter.Emit(second);

        Assert.Equal(firstResult.CatalogFingerprint, secondResult.CatalogFingerprint);
        Assert.Equal(
            Assert.Single(Assert.IsType<Cohesive.CodeGen.CodeEmission>(firstResult.Emission).Documents).Text,
            Assert.Single(Assert.IsType<Cohesive.CodeGen.CodeEmission>(secondResult.Emission).Documents).Text);
    }

    [Theory]
    [InlineData("EquipmentId")]
    [InlineData("EquipmentIds")]
    public void Emit_SingularOrPluralReferenceSuffix_ProducesSameRelationshipMember(string sourceReference)
    {
        var catalog = new RelationshipCatalog(
        [
            Relationship(
                $"load.{sourceReference}",
                Shape("domain/v1", "Load"),
                sourceReference,
                Shape("domain/v1", "Equipment"))
        ]);

        var result = new CSharpRelationshipCatalogEmitter(new()
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(catalog);
        var text = Assert.Single(Assert.IsType<Cohesive.CodeGen.CodeEmission>(result.Emission).Documents).Text;

        Assert.Contains("RelationshipId Equipment =", text, StringComparison.Ordinal);
        AssertCompiles(text);
    }

    [Fact]
    public void Emit_NormalizedGroupCollision_ReturnsDiagnosticWithoutEmission()
    {
        var firstSource = Shape(graphId: "domain/v1", shapeId: "domain.Load");
        var secondSource = Shape(graphId: "import/v2", shapeId: "custom.load/v3");
        var catalog = new RelationshipCatalog(
        [
            Relationship("load.customer", firstSource, "CustomerId", Shape("domain/v1", "Customer")),
            Relationship("load.equipment", secondSource, "EquipmentId", Shape("domain/v1", "Equipment"))
        ]);

        var result = new CSharpRelationshipCatalogEmitter().Emit(catalog);

        Assert.False(result.Succeeded);
        Assert.Null(result.Emission);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal("csharpRelationshipCatalog.groupSymbolCollision", diagnostic.Code);
        Assert.Equal(Cohesive.Model.DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("'Load'", diagnostic.Message, StringComparison.Ordinal);
        Assert.Equal(RelationshipCatalogFingerprinter.Compute(catalog), result.CatalogFingerprint);
    }

    [Fact]
    public void Emit_NormalizedMemberCollision_ReturnsDiagnosticWithoutEmission()
    {
        var source = Shape(graphId: "domain/v1", shapeId: "custom.load/v3");
        var catalog = new RelationshipCatalog(
        [
            Relationship("load.equipment.single", source, "EquipmentId", Shape("domain/v1", "Equipment")),
            Relationship("load.equipment.many", source, "EquipmentIds", Shape("domain/v1", "Equipment"))
        ]);

        var result = new CSharpRelationshipCatalogEmitter().Emit(catalog);

        Assert.False(result.Succeeded);
        Assert.Null(result.Emission);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal("csharpRelationshipCatalog.memberSymbolCollision", diagnostic.Code);
        Assert.Equal(Cohesive.Model.DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("'Equipment'", diagnostic.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_InvalidCatalog_ReturnsCatalogDiagnosticsWithoutEmission()
    {
        var source = Shape(graphId: "domain/v1", shapeId: "Load");
        var catalog = new RelationshipCatalog(
        [
            Relationship("duplicate", source, "CustomerId", Shape("domain/v1", "Customer")),
            Relationship("duplicate", source, "EquipmentId", Shape("domain/v1", "Equipment")),
            Relationship("invalid-enum", source, "TrailerId", Shape("domain/v1", "Trailer")) with
            {
                SourceReferenceUniqueness = (SourceReferenceUniqueness)999
            }
        ]);

        var result = new CSharpRelationshipCatalogEmitter().Emit(catalog);

        Assert.False(result.Succeeded);
        Assert.Null(result.Emission);
        Assert.Contains(result.Diagnostics, static diagnostic =>
            diagnostic.Code == "relationshipCatalog.relationship.duplicateId");
        Assert.Contains(result.Diagnostics, static diagnostic =>
            diagnostic.Code == "relationshipCatalog.relationship.conflictingId");
        Assert.Contains(result.Diagnostics, static diagnostic =>
            diagnostic.Code == "relationshipCatalog.relationship.sourceReferenceUniquenessInvalid");
        Assert.Null(result.CatalogFingerprint);
    }

    [Fact]
    public void Emit_KeywordConfigurationAndStringContent_EscapesValidCSharpSource()
    {
        var source = Shape(graphId: "domain/v1", shapeId: "Load");
        var catalog = new RelationshipCatalog(
        [
            Relationship(
                "load.\"customer\"\\lookup\nnext",
                source,
                "CustomerId",
                Shape("domain/v1", "Customer"))
        ]);
        var emitter = new CSharpRelationshipCatalogEmitter(new()
        {
            Namespace = "file.required",
            RootClassName = "record",
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        });

        var result = emitter.Emit(catalog);
        var text = Assert.Single(Assert.IsType<Cohesive.CodeGen.CodeEmission>(result.Emission).Documents).Text;

        Assert.Contains("namespace @file.@required;", text, StringComparison.Ordinal);
        Assert.Contains("public static class @record", text, StringComparison.Ordinal);
        Assert.Contains("new(\"load.\\\"customer\\\"\\\\lookup\\nnext\")", text, StringComparison.Ordinal);
        AssertCompiles(text);
    }

    static RelationshipCatalog CreateLoadCatalog()
    {
        var load = Shape(graphId: "domain/v1", shapeId: "custom.load/v3");
        return new(
        [
            Relationship(
                "domain.load.equipment",
                load,
                "EquipmentIds",
                Shape(graphId: "domain/v1", shapeId: "custom.equipment/v4")),
            Relationship(
                "domain.load.customer",
                load,
                "CustomerId",
                Shape(graphId: "domain/v1", shapeId: "custom.customer/v2"))
        ]);
    }

    static RelationshipDefinition Relationship(
        string id,
        QualifiedShapeId source,
        string sourceReference,
        QualifiedShapeId target) =>
        new(
            new RelationshipId(id),
            source,
            FieldPath.FromField(sourceReference),
            target,
            ObservationIdentityRelationshipTargetKey.Instance);

    static QualifiedShapeId Shape(string graphId, string shapeId) =>
        new(new GraphId(graphId), new ShapeId(shapeId));

    static void AssertCompiles(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(
            source,
            new CSharpParseOptions(documentationMode: DocumentationMode.Diagnose));
        var syntaxErrors = syntaxTree.GetDiagnostics()
            .Where(static diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error)
            .ToArray();
        Assert.True(syntaxErrors.Length == 0, string.Join(Environment.NewLine, syntaxErrors.Select(static diagnostic => diagnostic.ToString())));

        var trustedPlatformAssemblies = Assert.IsType<string>(
            AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"));
        var references = trustedPlatformAssemblies
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Append(typeof(RelationshipId).Assembly.Location)
            .Distinct(StringComparer.Ordinal)
            .Select(static path => MetadataReference.CreateFromFile(path));
        var compilation = CSharpCompilation.Create(
            assemblyName: "Cohesive.Generated.Relationships.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithSpecificDiagnosticOptions(new Dictionary<string, ReportDiagnostic>
                {
                    ["CS1591"] = ReportDiagnostic.Error
                }));

        using MemoryStream assembly = new();
        var emit = compilation.Emit(assembly);
        Assert.True(
            emit.Success,
            string.Join(
                Environment.NewLine,
                emit.Diagnostics
                    .Where(static diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error)
                    .Select(static diagnostic => diagnostic.ToString())));
    }
}
