using Cohesive.Adapters.TypeScript;
using Cohesive.CodeGen;
using Cohesive.CodeGen.Cli;
using Cohesive.Model;
using Cohesive.Presentation;

namespace Cohesive.Tests.CodeGen;

public sealed class PresentationContractProjectionTests
{
    [Fact]
    public void PresentationContracts_ProjectTheSharedAverageAggregateOperator()
    {
        var text = EmitPresentationContracts();

        Assert.Contains(
            "export type AggregateOperator = 0 | 1 | 2 | 3 | 4 | 5 | 6;",
            text,
            StringComparison.Ordinal);
        Assert.Contains("  average: 6,", text, StringComparison.Ordinal);
        Assert.Contains("  6: 'Average',", text, StringComparison.Ordinal);
    }

    [Fact]
    public void PresentationTypeScriptArtifact_IsCurrent()
    {
        var expected = EmitPresentationContracts();
        var path = Path.Combine(
            FindRepoRoot(),
            "src",
            "frontend",
            "presentation-contracts",
            "src",
            "generated",
            "cohesive.shapes.generated.ts");

        Assert.True(File.Exists(path), $"Missing generated presentation artifact '{path}'.");
        Assert.Equal(expected, File.ReadAllText(path));
    }

    static string EmitPresentationContracts()
    {
        var graph = ContractsAssemblyShapeGraphLoader.Load(
            typeof(DataSourceDefinition).Assembly.Location,
            moduleName: "cohesive");
        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            FileName = "cohesive.shapes.generated.ts",
            NewLine = "\n",
            EmitAutoGeneratedHeader = true
        }).Emit(new ShapeCodeGenerationRequest(graph));

        return Assert.Single(emission.Documents).Text;
    }

    static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Cohesive.sln")))
                return directory.FullName;

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }
}
