using Cohesive.Adapters.TypeScript;
using Cohesive.CodeGen;
using Cohesive.CodeGen.Cli;
using Cohesive.Model;
using Cohesive.Relations.Contracts;
using Cohesive.Relations.IR;
using Cohesive.Relations.Serialization;

namespace Cohesive.Tests.CodeGen;

public sealed class RelationsContractProjectionTests
{
    [Fact]
    public void RelationsContracts_ProjectRelationQueryDocumentAndClosedUnions()
    {
        var graph = ContractsAssemblyShapeGraphLoader.Load(
            typeof(RelationsContractsDefinition).Assembly.Location,
            moduleName: "relations");

        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationQueryDocument), StringComparison.Ordinal));
        AssertUnion(graph, nameof(RelationQueryDefinition), RelationQueryWireNames.DefinitionDiscriminator);
        AssertUnion(graph, nameof(LogicalQueryNode), RelationQueryWireNames.NodeDiscriminator);
        AssertUnion(graph, nameof(QueryResultDefinition), RelationQueryWireNames.ResultDiscriminator);
        AssertUnion(graph, nameof(QueryPageDefinition), RelationQueryWireNames.PageDiscriminator);

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(new ShapeCodeGenerationRequest(graph));
        var text = Assert.Single(emission.Documents).Text;

        Assert.Contains("export interface RelationQueryDocument", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationQueryDefinition =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $definition: 'relation';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $definition: 'query';", text, StringComparison.Ordinal);
        Assert.Contains("export type LogicalQueryNode =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'expandCollection';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'project';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'aggregate';", text, StringComparison.Ordinal);
    }

    static void AssertUnion(ShapeGraph graph, string name, string discriminator)
    {
        var union = Assert.IsType<TypeDefinition.Union>(
            Assert.Single(graph.NamedTypes, type => type.Name == name));
        Assert.Equal(discriminator, union.Discriminator.FieldName);
        Assert.NotEmpty(union.Cases);
    }
}
