using Cohesive.Adapters.TypeScript;
using Cohesive.CodeGen;
using Cohesive.CodeGen.Cli;
using Cohesive.Relations.Contracts;
using Cohesive.Relations.Drafts;
using Cohesive.Relations.IR;
using Cohesive.Relations.Model;
using Cohesive.Relations.Realization;

namespace Cohesive.Tests.CodeGen;

public sealed class RelationsContractProjectionTests
{
    [Fact]
    public void RelationsContracts_ProjectCanonicalDocumentsAndClosedUnions()
    {
        var graph = LoadWireContractGraph();

        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationQueryDocument), StringComparison.Ordinal));
        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationshipCatalogDocument), StringComparison.Ordinal));
        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationDraftDocument), StringComparison.Ordinal));
        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationQueryTargetCapabilityProfile), StringComparison.Ordinal));
        Assert.Contains(graph.Shapes, shape =>
            shape.Id.Value.EndsWith(nameof(RelationQueryRealizationReport), StringComparison.Ordinal));
        AssertUnion(graph, nameof(RelationQueryDefinition), RelationQueryWireNames.DefinitionDiscriminator);
        AssertUnion(graph, nameof(LogicalQueryNode), RelationQueryWireNames.NodeDiscriminator);
        AssertUnion(graph, nameof(QueryResultDefinition), RelationQueryWireNames.ResultDiscriminator);
        AssertUnion(graph, nameof(QueryPageDefinition), RelationQueryWireNames.PageDiscriminator);
        AssertUnion(graph, nameof(TemporalJoinMatch), RelationQueryWireNames.TemporalMatchDiscriminator);
        AssertUnion(graph, nameof(TemporalIntervalBound), RelationQueryWireNames.TemporalBoundDiscriminator);
        AssertUnion(graph, nameof(RelationshipTargetKey), RelationshipWireNames.TargetKeyDiscriminator);
        AssertUnion(
            graph,
            nameof(RelationDraftAssignmentResolution),
            RelationDraftWireNames.ResolutionDiscriminator);
        AssertUnion(
            graph,
            nameof(RelationQueryCapability),
            RelationQueryRealizationWireNames.CapabilityDiscriminator);
        AssertUnion(
            graph,
            nameof(RelationQueryRealizationDecision),
            RelationQueryRealizationWireNames.DecisionDiscriminator);

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(new ShapeCodeGenerationRequest(graph));
        var text = Assert.Single(emission.Documents).Text;

        Assert.Contains("export interface RelationQueryDocument", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationQueryDefinition =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $definition: 'relation';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $definition: 'query';", text, StringComparison.Ordinal);
        Assert.Contains("export type LogicalQueryNode =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'expandCollection';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'project';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'aggregate';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $node: 'temporalJoin';", text, StringComparison.Ordinal);
        Assert.Contains("export type TemporalJoinMatch =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $temporalMatch: 'pointInInterval';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $temporalMatch: 'intervalOverlap';", text, StringComparison.Ordinal);
        Assert.Contains("export type TemporalIntervalBound =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $temporalBound: 'unbounded';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $temporalBound: 'expression';", text, StringComparison.Ordinal);
        Assert.Contains("export interface RelationshipCatalogDocument", text, StringComparison.Ordinal);
        Assert.Contains("export interface RelationDraftDocument", text, StringComparison.Ordinal);
        Assert.Contains("export interface RelationQueryTargetCapabilityProfile", text, StringComparison.Ordinal);
        Assert.Contains("export interface RelationQueryRealizationReport", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationQueryCapability =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $capability: 'logical';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $capability: 'expression';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $capability: 'temporal';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $capability: 'operatingBoundaryValidation';", text, StringComparison.Ordinal);
        Assert.Contains(
            "kind: RelationQueryLogicalCapabilityKind | number;",
            text,
            StringComparison.Ordinal);
        Assert.Contains(
            "requirementKind: ExprCapabilityRequirementKind | number;",
            text,
            StringComparison.Ordinal);
        Assert.Contains(
            "kind: RelationQueryOperatingBoundaryKind | number;",
            text,
            StringComparison.Ordinal);
        Assert.Contains("export type RelationQueryRealizationDecision =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $decision: 'native';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $decision: 'composed';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $decision: 'constrained';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $decision: 'override';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $decision: 'unavailable';", text, StringComparison.Ordinal);
        Assert.Contains("requiredGuarantees: RelationQueryGuaranteeCapabilityKind[];", text, StringComparison.Ordinal);
        Assert.Contains("staticFacts: RelationQueryRealizationStaticFact[];", text, StringComparison.Ordinal);
        Assert.Contains("boundaryValidations: RelationQueryOperatingBoundaryValidation[];", text, StringComparison.Ordinal);
        Assert.Contains("limit?: string | null;", text, StringComparison.Ordinal);
        Assert.Contains("value: string;", text, StringComparison.Ordinal);
        Assert.Contains("measuredValue?: string | null;", text, StringComparison.Ordinal);
        Assert.Contains("'AlwaysPresentBinding' | 'MayBeAbsentBinding'", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationDraftAssignmentResolution =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $resolution: 'selected';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $resolution: 'omitted';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $resolution: 'unresolved';", text, StringComparison.Ordinal);
        Assert.Contains("readonly $resolution: 'ambiguous';", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationshipTargetKey =", text, StringComparison.Ordinal);
        Assert.Contains("readonly $targetKey: 'observationIdentity';", text, StringComparison.Ordinal);
        Assert.Contains("export type SourceReferenceUniqueness =", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationshipTraversalDirection =", text, StringComparison.Ordinal);
        Assert.Contains("schemaVersion: string;", text, StringComparison.Ordinal);
        Assert.Contains("sourceShape: QualifiedShapeId;", text, StringComparison.Ordinal);
        Assert.Contains("graphId: GraphId;", text, StringComparison.Ordinal);
        Assert.Contains("export type GraphId = string;", text, StringComparison.Ordinal);
        Assert.Contains("export type RelationshipId = string;", text, StringComparison.Ordinal);
        Assert.Contains(
            "export type RelationshipTraversalDirection = 'Forward' | 'Inverse';",
            text,
            StringComparison.Ordinal);
        Assert.Contains("annotations: Record<string, AnnotationValue>;", text, StringComparison.Ordinal);
        Assert.Contains("export type AnnotationValue = unknown;", text, StringComparison.Ordinal);
        Assert.Contains("binding?: ValueBindingId | null;", text, StringComparison.Ordinal);
        Assert.Contains("entity?: EntityId | null;", text, StringComparison.Ordinal);
        Assert.Contains(
            "inferenceDiagnostic?: TypeInferenceDiagnostic | null;",
            text,
            StringComparison.Ordinal);
        Assert.Contains("message?: string | null;", text, StringComparison.Ordinal);
        Assert.DoesNotContain("\n  SchemaVersion:", text, StringComparison.Ordinal);
        Assert.DoesNotContain("export interface RelationshipId", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Annotations: ({", text, StringComparison.Ordinal);
        Assert.DoesNotContain("kind: RelationQueryRealizationDecisionKind;", text, StringComparison.Ordinal);
        Assert.DoesNotContain("isRealizable: boolean;", text, StringComparison.Ordinal);
    }

    [Fact]
    public void RelationsTypeScriptArtifact_IsCurrent()
    {
        var graph = LoadWireContractGraph();
        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            FileName = "relations.shapes.generated.ts",
            NewLine = "\n",
            EmitAutoGeneratedHeader = true
        }).Emit(new ShapeCodeGenerationRequest(graph));
        var expected = Assert.Single(emission.Documents).Text;
        var path = Path.Combine(
            FindRepoRoot(),
            "src",
            "frontend",
            "relations",
            "src",
            "generated",
            "relations.shapes.generated.ts");

        Assert.True(File.Exists(path), $"Missing generated relations artifact '{path}'.");
        Assert.Equal(expected, File.ReadAllText(path));
    }

    static ShapeGraph LoadWireContractGraph() => ContractsAssemblyShapeGraphLoader.Load(
        typeof(RelationsContractsDefinition).Assembly.Location,
        moduleName: "relations",
        jsonSerializerOptions: RelationQueryJsonSerializer.CreateOptions());

    static void AssertUnion(ShapeGraph graph, string name, string discriminator)
    {
        var union = Assert.IsType<TypeDefinition.Union>(
            Assert.Single(graph.NamedTypes, type => type.Name == name));
        Assert.Equal(discriminator, union.Discriminator.FieldName);
        Assert.NotEmpty(union.Cases);
    }

    static string FindRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Cohesive.sln")))
                return directory.FullName;

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }
}
