using Cohesive.Adapters.TypeScript;
using Cohesive.CodeGen;

namespace Cohesive.Tests.CodeGen;

public sealed class TypeScriptContractConstantsEmitterTests
{
    [Fact]
    public void Emit_Constants_GeneratesConstObjects()
    {
        var constants = new ContractConstantSet(
            [
                new(
                    name: "TrainingNavigationRouteIds",
                    namespaceName: "Sample.Training.Api",
                    constants:
                    [
                        new("EdiSpecEditor", typeof(string), "edi-spec-editor"),
                        new("Home", typeof(string), "home")
                    ])
            ]);

        var emission = new TypeScriptContractConstantsEmitter(new TypeScriptEmitterOptions
        {
            FileName = "sample.constants.generated.ts",
            EmitAutoGeneratedHeader = false
        }).Emit(constants);

        var text = emission.Documents.Single().Text;
        Assert.Contains("export const trainingNavigationRouteIds = {", text);
        Assert.Contains("ediSpecEditor: 'edi-spec-editor',", text);
        Assert.Contains("home: 'home',", text);
        Assert.Contains("} as const", text);
    }
}
