using Cohesive.Adapters.TypeScript;
using Cohesive.CodeGen;
using Cohesive.Model.Serialization;
using Cohesive.Presentation;

namespace Cohesive.Tests.CodeGen;

public sealed class TypeScriptShapeEmitterTests
{
    [Fact]
    public void Emit_PocoGraph_GeneratesTypeScriptForReactFriendlyDtos()
    {
        var graph = new ClrShapeGraphBuilder()
            .AddShape<ShipmentDto>(ShapeRoles.Entity)
            .Build();

        Assert.Single(graph.Shapes);
        Assert.Contains(graph.NamedTypes, x => x.Id.Value.EndsWith(nameof(RouteStopDto), StringComparison.Ordinal));
        Assert.Contains(graph.NamedTypes, x => x.Id.Value.EndsWith(nameof(ShipmentStatus), StringComparison.Ordinal));

        var emitter = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            FileName = "shipment.generated.ts",
            NewLine = "\n",
            EmitAutoGeneratedHeader = true
        });

        var emission = emitter.Emit(new ShapeCodeGenerationRequest(graph));
        var document = Assert.Single(emission.Documents);

        Assert.Equal("typescript", emission.Language);
        Assert.Equal("shipment.generated.ts", document.FileName);
        Assert.Contains("/* <auto-generated/> */", document.Text, StringComparison.Ordinal);
        Assert.Contains("export type ShipmentStatus = 0 | 1;", document.Text, StringComparison.Ordinal);
        Assert.Contains("export const shipmentStatuses = {\n  pending: 0,\n  confirmed: 1,\n} as const satisfies Record<string, ShipmentStatus>;", document.Text, StringComparison.Ordinal);
        Assert.Contains("export const shipmentStatusLabels: Record<ShipmentStatus, string> = {\n  0: 'Pending',\n  1: 'Confirmed',\n};", document.Text, StringComparison.Ordinal);
        Assert.Contains("export interface RouteStopDto", document.Text, StringComparison.Ordinal);
        Assert.Contains("DelayHours?: number | null;", document.Text, StringComparison.Ordinal);
        Assert.Contains("export interface ShipmentDto", document.Text, StringComparison.Ordinal);
        Assert.Contains("Status: ShipmentStatus;", document.Text, StringComparison.Ordinal);
        Assert.Contains("Distance: number;", document.Text, StringComparison.Ordinal);
        Assert.Contains("Stops: RouteStopDto[];", document.Text, StringComparison.Ordinal);
        Assert.Contains("Notes?: string | null;", document.Text, StringComparison.Ordinal);
        Assert.Equal(1, CountOccurrences(document.Text, "export interface ShipmentDto"));
    }

    [Fact]
    public void Emit_EnumLabelMap_UsesClrCodeMetadataWithoutChangingNumericContract()
    {
        var graph = new ClrShapeGraphBuilder()
            .AddShape<LabeledShipmentDto>(ShapeRoles.ValueObject)
            .Build();

        var statusType = Assert.IsType<TypeDefinition.Enum>(
            Assert.Single(graph.NamedTypes, type => type.Name == nameof(LabeledShipmentStatus)));
        Assert.Contains(statusType.Values, value =>
            value.Name == nameof(LabeledShipmentStatus.AwaitingPickup)
            && value.Value == "0"
            && value.Label == "Awaiting pickup"
            && value.Description == "Waiting for dock assignment.");
        Assert.Contains(statusType.Values, value =>
            value.Name == nameof(LabeledShipmentStatus.Loaded)
            && value.Value == "1"
            && value.Label == "Loaded on trailer"
            && value.Description == "Freight has left the dock.");

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(new ShapeCodeGenerationRequest(graph));

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("export type LabeledShipmentStatus = 0 | 1;", text, StringComparison.Ordinal);
        Assert.Contains("export const labeledShipmentStatuses = {\n  awaitingPickup: 0,\n  loaded: 1,\n} as const satisfies Record<string, LabeledShipmentStatus>;", text, StringComparison.Ordinal);
        Assert.Contains("export const labeledShipmentStatusLabels: Record<LabeledShipmentStatus, string> = {\n  0: 'Awaiting pickup',\n  1: 'Loaded on trailer',\n};", text, StringComparison.Ordinal);
        Assert.Contains("Status: LabeledShipmentStatus;", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_IrFirstGraph_UsesNamedTypesWithoutClrReflection()
    {
        var statusType = new TypeDefinition.Enum(
            id: new TypeId("type:orderStatus"),
            underlying: PrimitiveType.String,
            values:
            [
                new EnumValue("Pending"),
                new EnumValue("Completed")
            ]);

        var addressType = new TypeDefinition.Structural(
            id: new TypeId("type:address"),
            fields:
            [
                new StructuralField(new FieldName("Street"), new ScalarTypeRef(ScalarTypeKind.String)),
                new StructuralField(
                    new FieldName("PostalCode"),
                    new ScalarTypeRef(ScalarTypeKind.String),
                    presence: FieldPresence.Optional,
                    nullability: FieldNullability.Nullable)
            ]);

        var orderShape = new Shape(
            id: new ShapeId("shape:order"),
            role: ShapeRoles.Entity,
            fields:
            [
                new FieldDefinition(
                    name: new FieldName("Id"),
                    type: new ScalarTypeRef(ScalarTypeKind.String)),
                new FieldDefinition(
                    name: new FieldName("Status"),
                    type: new NamedTypeRef(statusType.Id)),
                new FieldDefinition(
                    name: new FieldName("ShipTo"),
                    type: new NamedTypeRef(addressType.Id))
            ]);

        var request = ShapeCodeGenerationRequest.FromShape(orderShape, [statusType, addressType]);
        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(request);

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("export type OrderStatus = 'Pending' | 'Completed';", text, StringComparison.Ordinal);
        Assert.Contains("export const orderStatuses = {\n  pending: 'Pending',\n  completed: 'Completed',\n} as const satisfies Record<string, OrderStatus>;", text, StringComparison.Ordinal);
        Assert.Contains("export const orderStatusLabels: Record<OrderStatus, string> = {\n  Pending: 'Pending',\n  Completed: 'Completed',\n};", text, StringComparison.Ordinal);
        Assert.Contains("export interface Address", text, StringComparison.Ordinal);
        Assert.Contains("PostalCode?: string | null;", text, StringComparison.Ordinal);
        Assert.Contains("export interface Order", text, StringComparison.Ordinal);
        Assert.Contains("ShipTo: Address;", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_UndefinedNumericEnumField_PreservesCardinalityAndNullability()
    {
        var statusType = new TypeDefinition.Enum(
            id: new TypeId("type:OpenStatus"),
            underlying: PrimitiveType.String,
            values: [new EnumValue("Known")]);
        var containerShape = new Shape(
            id: new ShapeId("shape:OpenEnumContainer"),
            fields:
            [
                new FieldDefinition(
                    name: new FieldName("OpenValues"),
                    type: new NamedTypeRef(statusType.Id),
                    cardinality: FieldCardinality.Many,
                    nullability: FieldNullability.Nullable,
                    annotations: AnnotationMap.Create(
                        SystemTextJsonShapeAnnotations.UndefinedNumericEnumValues,
                        true))
            ]);

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(ShapeCodeGenerationRequest.FromShape(containerShape, [statusType]));

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("OpenValues: (OpenStatus | number)[] | null;", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_InlineObjectFields_PreserveModifiersAndClosedEmptyObjects()
    {
        var containerShape = new Shape(
            id: new ShapeId("shape:InlineObjectContainer"),
            fields:
            [
                new FieldDefinition(
                    name: new FieldName("Payload"),
                    type: new ObjectTypeRef(
                    [
                        new ObjectFieldTypeDef(
                            name: "Values",
                            type: new ScalarTypeRef(ScalarTypeKind.String),
                            cardinality: FieldCardinality.Many,
                            presence: FieldPresence.Optional,
                            nullability: FieldNullability.Nullable),
                        new ObjectFieldTypeDef(
                            name: "Empty",
                            type: new ObjectTypeRef([]))
                    ]))
            ]);

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(ShapeCodeGenerationRequest.FromShape(containerShape));

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("Values?: string[] | null;", text, StringComparison.Ordinal);
        Assert.Contains("Empty: Record<never, never>;", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_PresentationModule_IncludesExpressionAndTypeReferenceUnions()
    {
        var graph = new ClrShapeGraphBuilder()
            .AddShape(typeof(PresentationModuleDefinition))
            .Build();

        var expr = Assert.IsType<TypeDefinition.Union>(
            Assert.Single(graph.NamedTypes, type => type.Name == nameof(Expr)));
        Assert.Equal("$expr", expr.Discriminator.FieldName);
        Assert.Contains(expr.Cases, @case => @case.DiscriminatorValue == "parameter");

        var typeRef = Assert.IsType<TypeDefinition.Union>(
            Assert.Single(graph.NamedTypes, type => type.Name == nameof(TypeRef)));
        Assert.Equal("$type", typeRef.Discriminator.FieldName);
        Assert.Contains(typeRef.Cases, @case => @case.DiscriminatorValue == "scalar");

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            NewLine = "\n"
        }).Emit(new ShapeCodeGenerationRequest(graph));

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("export interface PresentationExpressionDefinition", text, StringComparison.Ordinal);
        Assert.Contains("export interface WorkspaceDefinition", text, StringComparison.Ordinal);
        Assert.Contains("Workspaces: WorkspaceDefinition[];", text, StringComparison.Ordinal);
        Assert.Contains("export interface DocumentProfileDefinition", text, StringComparison.Ordinal);
        Assert.Contains("DocumentProfiles: DocumentProfileDefinition[];", text, StringComparison.Ordinal);
        Assert.Contains("export interface WorkspaceRefDefinition", text, StringComparison.Ordinal);
        Assert.Contains("Workspace?: WorkspaceRefDefinition | null;", text, StringComparison.Ordinal);
        Assert.Contains("export interface ProjectionDefinition", text, StringComparison.Ordinal);
        Assert.Contains("export interface SemanticSelection", text, StringComparison.Ordinal);
        Assert.Contains("export interface WorkspaceLayoutDefinition", text, StringComparison.Ordinal);
        Assert.Contains("Expression: Expr;", text, StringComparison.Ordinal);
        Assert.Contains("ReturnType?: TypeRef | null;", text, StringComparison.Ordinal);
        Assert.Contains("export type Expr = ", text, StringComparison.Ordinal);
        Assert.Contains("readonly $expr: 'parameter';", text, StringComparison.Ordinal);
        Assert.Contains("export interface ParameterExpr", text, StringComparison.Ordinal);
        Assert.Contains("export type CurrentItemExpr = Record<never, never>;", text, StringComparison.Ordinal);
        Assert.Contains("export type TypeRef = ", text, StringComparison.Ordinal);
        Assert.Contains("readonly $type: 'scalar';", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_ExternalTypeModules_ImportsAndReexportsExternalShapeTypes()
    {
        var graph = new ClrShapeGraphBuilder()
            .AddShape<PresentationEnvelope>()
            .Build();

        var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
        {
            EmitAutoGeneratedHeader = false,
            ExternalTypeModules =
            [
                new TypeScriptExternalTypeModule
                {
                    TypeIdPrefix = "clr:type:Cohesive.Presentation.",
                    ShapeIdPrefix = "clr:shape:Cohesive.Presentation.",
                    ImportPath = "./cohesive.shapes.generated"
                },
                new TypeScriptExternalTypeModule
                {
                    TypeIdPrefix = "clr:type:Cohesive.Model.",
                    ShapeIdPrefix = "clr:shape:Cohesive.Model.",
                    ImportPath = "./cohesive.shapes.generated"
                }
            ],
            NewLine = "\n"
        }).Emit(new ShapeCodeGenerationRequest(graph));

        var text = Assert.Single(emission.Documents).Text;
        Assert.Contains("import type {", text, StringComparison.Ordinal);
        Assert.Contains("PresentationModuleDefinition", text, StringComparison.Ordinal);
        Assert.Contains("} from './cohesive.shapes.generated';", text, StringComparison.Ordinal);
        Assert.Contains("export type {", text, StringComparison.Ordinal);
        Assert.DoesNotContain("export interface PresentationModuleDefinition", text, StringComparison.Ordinal);
        Assert.Contains("export interface PresentationEnvelope", text, StringComparison.Ordinal);
        Assert.Contains("Module: PresentationModuleDefinition;", text, StringComparison.Ordinal);
    }

    static int CountOccurrences(string text, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }

    sealed record ShipmentDto(
        string Id,
        ShipmentStatus Status,
        Distance Distance,
        IReadOnlyList<RouteStopDto> Stops,
        string? Notes,
        DateTimeOffset UpdatedAt);

    sealed record PresentationEnvelope(string Id, PresentationModuleDefinition Module);

    sealed record RouteStopDto(string Code, decimal? DelayHours);

    enum ShipmentStatus
    {
        Pending = 0,
        Confirmed = 1
    }
}

sealed record LabeledShipmentDto(LabeledShipmentStatus Status);

public enum LabeledShipmentStatus
{
    [CodeSet("Awaiting pickup", Description = "Waiting for dock assignment.")]
    AwaitingPickup = 0,

    [Code("loaded", Label = "Loaded on trailer", Description = "Freight has left the dock.")]
    Loaded = 1
}
