using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;
using Cohesive.Infra.Local;

namespace Cohesive.Adapters.Aspire;

/// <summary>Associates a canonical project identity with native Aspire generated project metadata.</summary>
/// <remarks>The association is runtime-only. Metadata and callbacks never enter canonical Infra documents.</remarks>
public sealed class AspireProjectAssociation
{
    readonly Func<IDistributedApplicationBuilder, string, string?, IResourceBuilder<ProjectResource>> add;

    AspireProjectAssociation(InfrastructureLocalProjectId id,
        Func<IDistributedApplicationBuilder, string, string?, IResourceBuilder<ProjectResource>> add)
    {
        if (string.IsNullOrWhiteSpace(id.Value))
            throw new ArgumentException("A native project association requires a canonical project identity.", nameof(id));
        Id = id;
        this.add = add;
    }

    /// <summary>The canonical project being materialized.</summary>
    public InfrastructureLocalProjectId Id { get; }

    /// <summary>Uses Aspire's native AddProject API with the generated metadata type from a ProjectReference.</summary>
    /// <typeparam name="TProject">Native project metadata generated by the Aspire SDK.</typeparam>
    /// <param name="id">Canonical project identity declared without a repository path.</param>
    /// <returns>An immutable association; no project is constructed until the projection is applied.</returns>
    /// <exception cref="ArgumentException">The identity is default.</exception>
    public static AspireProjectAssociation Create<TProject>(InfrastructureLocalProjectId id)
        where TProject : IProjectMetadata, new() => new(id,
            static (builder, name, launchProfile) => builder.AddProject<TProject>(name, launchProfile));

    internal IResourceBuilder<ProjectResource> Add(IDistributedApplicationBuilder builder, string name, string? launchProfile) =>
        add(builder, name, launchProfile);
}
