using System.Text.Json;
using System.Text.Json.Serialization;
using Cohesive.Adapters.GraphQL;
using Cohesive.Adapters.TypeScript;
using Cohesive.Adapters.OpenApi;
using Cohesive.Api.CodeGen;
using Cohesive.CodeGen;
using Cohesive.Model;
using Cohesive.Model.Serialization;

namespace Cohesive.CodeGen.Cli;

/// <summary>
/// Generates code artifacts from contract assemblies.
/// </summary>
public static class ContractsCodeGenerator
{
    /// <summary>
    /// Generates one TypeScript file per requested artifact kind.
    /// </summary>
    public static int Generate(CodeGenCliOptions options, TextWriter log)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(log);

        var writes = 0;

        for (var i = 0; i < options.EmitKinds.Length; i++)
        {
            var emitKind = options.EmitKinds[i];
            switch (emitKind)
            {
                case CodeGenEmitKind.Shapes:
                {
                    var graph = LoadShapeGraph(options);
                    var emission = new TypeScriptShapeEmitter(new TypeScriptEmitterOptions
                    {
                        FileName = $"{SanitizeFileNameSegment(options.ModuleName)}.shapes.generated.ts",
                        NewLine = "\n",
                        EmitAutoGeneratedHeader = true,
                        ExternalTypeModules = options.ExternalTypeScriptShapeModules,
                        UnionDiscriminatorCatalogs = options.TypeScriptUnionDiscriminatorCatalogs
                    }).Emit(new ShapeCodeGenerationRequest(graph));

                    var document = emission.Documents[0];
                    var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                    var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                    log.WriteLine(changed
                        ? $"updated {outputPath}"
                        : $"unchanged {outputPath}");
                    if (changed)
                        writes++;
                    break;
                }

                case CodeGenEmitKind.Apis:
                {
                    var definition = ContractsAssemblyApiDefinitionLoader.Load(options.ContractsAssemblyPath);
                    var emission = new TypeScriptApiClientEmitter(new TypeScriptApiClientEmitterOptions
                    {
                        FileName = $"{SanitizeFileNameSegment(options.ModuleName)}.api.generated.ts",
                        ModuleName = options.ModuleName,
                        ShapesImportPath = $"./{SanitizeFileNameSegment(options.ModuleName)}.shapes.generated",
                        NewLine = "\n",
                        EmitAutoGeneratedHeader = true
                    }).Emit(new ApiCodeGenerationRequest(definition));

                    var document = emission.Documents[0];
                    var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                    var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                    log.WriteLine(changed
                        ? $"updated {outputPath}"
                        : $"unchanged {outputPath}");
                    if (changed)
                        writes++;
                    break;
                }

                case CodeGenEmitKind.OpenApi:
                {
                    var definition = ContractsAssemblyApiDefinitionLoader.Load(options.ContractsAssemblyPath);
                    var emission = new OpenApiEmitter(new OpenApiEmitterOptions
                    {
                        FileName = $"{SanitizeFileNameSegment(options.ModuleName)}.openapi.generated.json",
                        Title = options.ModuleName,
                        Version = "1.0.0",
                        WriteIndented = true
                    }).Emit(new ApiCodeGenerationRequest(definition));

                    var document = emission.Documents[0];
                    var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                    var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                    log.WriteLine(changed
                        ? $"updated {outputPath}"
                        : $"unchanged {outputPath}");
                    if (changed)
                        writes++;
                    break;
                }

                case CodeGenEmitKind.ApiPlaywright:
                {
                    var definition = ContractsAssemblyApiDefinitionLoader.Load(options.ContractsAssemblyPath);
                    var emission = new TypeScriptPlaywrightApiMockEmitter(new TypeScriptPlaywrightApiMockEmitterOptions
                    {
                        FileName = $"{SanitizeFileNameSegment(options.ModuleName)}.api.playwright.generated.ts",
                        ShapesImportPath = $"./{SanitizeFileNameSegment(options.ModuleName)}.shapes.generated",
                        ModuleName = options.ModuleName,
                        NewLine = "\n",
                        EmitAutoGeneratedHeader = true
                    }).Emit(new ApiCodeGenerationRequest(definition));

                    var document = emission.Documents[0];
                    var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                    var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                    log.WriteLine(changed
                        ? $"updated {outputPath}"
                        : $"unchanged {outputPath}");
                    if (changed)
                        writes++;
                    break;
                }

                case CodeGenEmitKind.GraphQL:
                {
                    var definition = ContractsAssemblyApiDefinitionLoader.Load(options.ContractsAssemblyPath);
                    var emission = new GraphQLSchemaEmitter(new GraphQLSchemaEmitterOptions
                    {
                        SchemaFileName = $"{SanitizeFileNameSegment(options.ModuleName)}.graphql.generated.graphql",
                        IntrospectionFileName = $"{SanitizeFileNameSegment(options.ModuleName)}.graphql.introspection.generated.json",
                        SchemaName = options.ModuleName,
                        IncludeCohesiveDirectives = true,
                        WriteIndented = true
                    }).Emit(new ApiCodeGenerationRequest(definition));

                    for (var documentIndex = 0; documentIndex < emission.Documents.Length; documentIndex++)
                    {
                        var document = emission.Documents[documentIndex];
                        var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                        var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                        log.WriteLine(changed
                            ? $"updated {outputPath}"
                            : $"unchanged {outputPath}");
                        if (changed)
                            writes++;
                    }

                    break;
                }

                case CodeGenEmitKind.Constants:
                {
                    var constants = ContractsAssemblyConstantsLoader.Load(options.ContractsAssemblyPath);
                    var emission = new TypeScriptContractConstantsEmitter(new TypeScriptEmitterOptions
                    {
                        FileName = $"{SanitizeFileNameSegment(options.ModuleName)}.constants.generated.ts",
                        NewLine = "\n",
                        EmitAutoGeneratedHeader = true
                    }).Emit(constants);

                    var document = emission.Documents[0];
                    var outputPath = Path.Combine(options.OutputDirectory, document.FileName);
                    var changed = GeneratedArtifactWriter.WriteIfChanged(outputPath, document.Text);
                    log.WriteLine(changed
                        ? $"updated {outputPath}"
                        : $"unchanged {outputPath}");
                    if (changed)
                        writes++;
                    break;
                }

                case CodeGenEmitKind.Transitions:
                case CodeGenEmitKind.Processes:
                case CodeGenEmitKind.Invariants:
                    throw new NotSupportedException(
                        $"Emit kind '{emitKind.ToString().ToLowerInvariant()}' is reserved but not implemented yet.");

                default:
                    throw new InvalidOperationException($"Unsupported emit kind '{emitKind}'.");
            }
        }

        return writes;
    }

    static string SanitizeFileNameSegment(string value)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        Span<char> initial = stackalloc char[64];
        var builder = new Cohesive.Prelude.ValueStringBuilder(initial);
        try
        {
            for (var i = 0; i < value.Length; i++)
            {
                var current = value[i];
                if (Array.IndexOf(invalidChars, current) >= 0)
                    builder.Append('_');
                else
                    builder.Append(current);
            }

            var result = builder.ToString();
            return string.IsNullOrWhiteSpace(result) ? "contracts" : result;
        }
        finally
        {
            builder.Dispose();
        }
    }

    static ShapeGraph LoadShapeGraph(CodeGenCliOptions options)
    {
        if (options.ShapeProjection == ContractShapeProjection.Clr)
            return ContractsAssemblyShapeGraphLoader.Load(options.ContractsAssemblyPath, options.ModuleName);

        if (options.ShapeProjection != ContractShapeProjection.CanonicalJson)
            throw new InvalidOperationException($"Unsupported shape projection '{options.ShapeProjection}'.");

        JsonSerializerOptions serializerOptions = new(JsonSerializerDefaults.Web);
        serializerOptions.Converters.Add(SingleValueWrapperJsonConverter.ScalarOnly);
        serializerOptions.Converters.Add(new JsonStringEnumConverter());
        return ContractsAssemblyShapeGraphLoader.Load(
            options.ContractsAssemblyPath,
            options.ModuleName,
            serializerOptions);
    }
}
