using System.Collections.Immutable;
using Cohesive.Infra;
using Cohesive.Infra.Realization;
using Cohesive.Model;

namespace Cohesive.Adapters.Pulumi.Azure;

/// <summary>Canonical ownership and explicit permission decisions for a native Entra application.</summary>
/// <remarks>Native SDK arguments own redirects, audience, scopes/roles and credentials. The policy contains no secrets.</remarks>
public sealed record AzureEntraPolicy
{
    /// <summary>External tenant dependency, never a managed directory.</summary>
    public required InfrastructureNodeId Tenant { get; init; }
    /// <summary>Managed application registration resource.</summary>
    public required InfrastructureNodeId Application { get; init; }
    /// <summary>Optional separately owned service principal for this application.</summary>
    public InfrastructureNodeId? ServicePrincipal { get; init; }
    /// <summary>Shared exclusive Pulumi lifecycle authority, formatted pulumi/project/stack.</summary>
    public required InfrastructureLifecycleAuthorityId LifecycleAuthority { get; init; }
    /// <summary>Tenant resolved by the caller's actual AzureAD provider configuration.</summary>
    public required Guid TenantId { get; init; }
    /// <summary>Canonical contract for requesting delegated access; does not imply consent.</summary>
    public required InfrastructureBindingContractId DelegatedAccessContract { get; init; }
    /// <summary>Canonical contract for explicitly assigned application roles.</summary>
    public required InfrastructureBindingContractId ApplicationAccessContract { get; init; }
    /// <summary>Exactly one attributed permission decision per participating incoming binding.</summary>
    public required ImmutableArray<AzureEntraPermission> Permissions { get; init; }
    /// <summary>Non-empty references attributing ownership, scope and permission policy.</summary>
    public required ImmutableArray<SourceReference> SourceReferences { get; init; }
}

/// <summary>Explicit supported authorization action; missing values never authorize access.</summary>
public enum AzureEntraPermissionAction
{
    /// <summary>Missing action, rejected.</summary>
    Unspecified = 0,
    /// <summary>Request a delegated scope in native required-resource-access configuration; consent remains unverified.</summary>
    RequestDelegatedScope = 1,
    /// <summary>Permit an explicit application-role assignment for the canonical source principal.</summary>
    AssignApplicationRole = 2
}

/// <summary>Attributed permission on one canonical incoming access edge.</summary>
/// <param name="Binding">Participating canonical binding.</param>
/// <param name="PermissionId">Existing explicit scope or role GUID, never regenerated by the adapter.</param>
/// <param name="Action">Request a scope or explicitly assign an application role.</param>
/// <param name="SourceReferences">Non-empty permission-policy references, not credential values.</param>
public sealed record AzureEntraPermission(InfrastructureBindingId Binding, Guid PermissionId,
    AzureEntraPermissionAction Action, ImmutableArray<SourceReference> SourceReferences);
