<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cohesive.Simulation.Cli\Cohesive.Simulation.Cli.csproj" />
    <ProjectReference Include="..\Cohesive.Simulation.ExternalProcess\Cohesive.Simulation.ExternalProcess.csproj" />
    <ProjectReference Include="..\Cohesive.Simulation.Relations\Cohesive.Simulation.Relations.csproj" />
    <ProjectReference Include="..\Cohesive.Simulation\Cohesive.Simulation.csproj" />
    <ProjectReference Include="..\Cohesive.Simulation.Storage\Cohesive.Simulation.Storage.csproj" />
    <ProjectReference Include="..\Cohesive.Simulation.Xunit\Cohesive.Simulation.Xunit.csproj" />
  </ItemGroup>

</Project>
