namespace Cohesive.Adapters.CSharp;

/// <summary>
/// Configures deterministic C# identifiers emitted from a canonical relationship catalog.
/// </summary>
public sealed record CSharpRelationshipCatalogEmitterOptions
{
    /// <summary>Namespace that contains the generated relationship identifier class.</summary>
    public string Namespace { get; init; } = "Cohesive.Generated";

    /// <summary>Name of the root static class that contains source-shape relationship groups.</summary>
    public string RootClassName { get; init; } = "DomainRelationships";

    /// <summary>Name assigned to the generated C# document.</summary>
    public string FileName { get; init; } = "DomainRelationships.g.cs";

    /// <summary>
    /// Line terminator used by the generated document. Supported values are <c>\n</c> and
    /// <c>\r\n</c>.
    /// </summary>
    public string NewLine { get; init; } = "\n";

    /// <summary>Whether the generated document begins with the standard auto-generated header.</summary>
    public bool EmitAutoGeneratedHeader { get; init; } = true;
}
