<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Cohesive.Infra/Cohesive.Infra.csproj" />
    <ProjectReference Include="../../../src/Cohesive.Relations/Cohesive.Relations.csproj" />
    <ProjectReference Include="../../../src/Cohesive.Storage/Cohesive.Storage.csproj" />
  </ItemGroup>
</Project>
